callstack/repack

README.md
examples/TesterApp/package-lock.json
src/server/DevServerProxy.ts
src/webpack/plugins/DevServerPlugin/DevServerPlugin.ts
templates/webpack.config.js

Initialize React DevTools (as part of `InitializeCore.js`) before initializing React Refresh to avoid the issue listed here: [https://github.com/facebook/react/issues/20377](https://github.com/facebook/react/issues/20377).
1. Run application
2. Open Flipper
3. Check React DevTools - it should show React component tree
4. Make more change in source code, the app should apply the update and component tree inside React DevTools should be updated.

fix: initialize React Devtools before React Refresh

---

ARCHITECTURE.md
README.md
src/Reporter.ts
src/server/DevServerProxy.ts
src/server/ws/WebSocketEventsServer.ts

This PR allows to see the development server logs inside connected Flipper instance in addition to the terminal, so one would be able to inspect and better filter/search for the logging information for debugging purposes.
1. Start development server e.g. run `npx react-native webpack-start`
2. Open Flipper and go to _React Native_ -> `Logs`
3. Loop for `rnwt_<type>` logs.

feat: report dev server logs to Flipper

---

examples/TesterApp/webpack.config.js
src/server/BaseDevServer.ts
src/types.ts
src/webpack/plugins/DevServerPlugin/DevServerPlugin.ts
src/webpack/plugins/LoggerPlugin.ts
src/webpack/utils/parseCliOptions.ts
templates/webpack.config.js

Add new option `enable` to `DevServerPlugin` to allow conditionally disable development server instead of passing `undefined` to `new DevServerPlugin(...)` call.
1. Create production bundle.
2. No `DevServerPlugin` change should be present inside the bundle (e.g. `__webpack_require__.p` - public path should be `''`)

fix: add `enable` option to DevServer for disabling the plugin instead of passing `undefined`

---

react-native.config.js
src/commands/bundle.ts
src/commands/start.ts
src/commands/utils/getWebpackConfigPath.ts
src/types.ts

Adds `--webpackConfig <path>` options to `webpack-start` and `webpack-bundle` commands.
1. Move/create Webpack config in non-default location eg `webpack-config.js`
2. Run `webpack-start`/`webpack-bundle` with `--webpackConfig ./webpack-config.js`
3. The code should not throw error

feat: add support for custom webpack location

---

src/webpack/utils/getResolveOptions.ts

We have some modules that import `.json` files without extension that fail when using this toolkit. The `.json` extension is included in the default webpack resolver settings, and work with metro so it makes sense for it to be included here too.

Add .json to resolver

---

src/server/BaseDevServer.ts
src/server/DevServer.ts
src/server/ws/WebSocketRouter.ts
src/server/ws/WebSocketServer.ts

Change the way the development server handles multiple WebSocket servers by adding a dedicated router, which allows to properly close all incoming connections that were not accepted by any WebSocket server. This prevent handling socket issue which (especially on Windows) can crash the process with `ECONNRESET` error.
1. Configure RNWT for React Native Windows.
2. Run `webpack-start` command.
2. Open React Native Windows application and load the bundle.
3. Wait for at least 30s.
4. App should not crash and the HMR should still work.

fix: destroy hanging sockets and prevent crash on Windows

---

android/src/main/java/com/callstack/nativepack/ChunkLoader.kt
android/src/main/java/com/callstack/nativepack/ChunkLoadingError.kt
android/src/main/java/com/callstack/nativepack/FileSystemChunkLoader.kt
android/src/main/java/com/callstack/nativepack/RemoteChunkLoader.kt
android/src/main/java/com/callstack/nativepack/WebpackToolkitModule.kt
android/src/main/java/com/callstack/nativepack/WebpackToolkitPackage.kt

This commit fixes the package name in the android
kotlin files which were missed in the project rename.
This fixes the webpack-bundle job not being able to
run for the android platform.
This fixes the webpack-bundle job not being able to
run for the android platform.
Manual

fix: package name in android kotlin files

---

examples/TesterApp/webpack.config.js
templates/webpack.config.js

After the project rename, the existing regexes for transpiling `node_module` dependencies no longer match `@callstack/nativepack`. This PR adds additional regex to `webpack.config.js` to avoid bugs like #27 
1. Run the application.
2. It should not throw unexpected errors.

fix: add explicit regex to transpile nativepack to webpack.config.js template

---

android/src/main/java/com/callstack/nativepack/ChunkLoader.kt
android/src/main/java/com/callstack/nativepack/ChunkLoadingError.kt
android/src/main/java/com/callstack/nativepack/ChunkManagerModule.kt
android/src/main/java/com/callstack/nativepack/FileSystemChunkLoader.kt
android/src/main/java/com/callstack/nativepack/RemoteChunkLoader.kt
examples/TesterApp/App.js
examples/TesterApp/Remote.js
examples/TesterApp/RemoteChunksSection.js
examples/TesterApp/babel.config.js
examples/TesterApp/index.js
src/client/chunks-api/ChunkManager.ts

Android support for remote chunks. Implementation of below methods on NativeModule:
- loadChunk - only improvements
- preloadChunk
- invalidateChunks
I added a Remote section in Tester app where user can test downloading chunk from a remote server. Creating a server with chunk is required in order to do that

feat: remote chunks android

---

src/runtime/setupChunkLoader.ts

Fixes #29 
1. Run the app with development server.
2. Make change to the source code that would trigger HMR update.
3. The update should be successfully applied.

fix: use global instead of this when evaluating HMR update

---

package.json

#22 introduced a regression in that the podspec was excluded from the release build of the package due to a naming mismatch. 
This PR fixes the name in the package whitelist.

Include podspec in release package

---

ios/ChunkManager.mm

Added method `runInBackground` which lets to run methods `loadChunk`, `preloadChunk` and `invalidateChunks` without blocking the UI thread for iOS.
Manually test `TesterApp` using 2s delay in methods `loadChunk`, `preloadChunk` and `invalidateChunks`.
The app is responsive hence UI thread is not blocked.
https://user-images.githubusercontent.com/12425395/120200366-b0cdc100-c23d-11eb-8b59-1dc07c7078c3.mov

feat: runInBackground thread for iOS

---

templates/webpack.config.js

Small regex change on babel loader in webpack to support windows.
n/a

fix: small windows support fix in babel loader in webpack config

---

templates/webpack.config.js

there was a syntax error beside I think mode is what I was searching for. outputs will be like `production.ios.log` and `development.ios.log`

fix: webpack.config.js LoggerPlugin file path

---

packages/TesterApp/webpack.config.js
packages/repack/src/client/chunks-api/ChunkManager.ts
packages/repack/src/client/runtime/setupChunkLoader.ts
packages/repack/src/client/shared/LoadEvent.ts
packages/repack/src/webpack/plugins/OutputPlugin.ts
packages/repack/src/webpack/plugins/utils/AssetsCopyProcessor.ts
packages/repack/src/webpack/plugins/utils/__tests__/AssetsCopyProcessor.test.ts
templates/webpack.config.js

Fixes #55 
1. Build TesterApp in release mode on iOS and Android
2. The app should load Async chunk and display it without any errors.

fix: use per-platform directories in OutputPlugin and improve error messages for chunk loading 

---

packages/repack/src/types.ts
packages/repack/src/webpack/plugins/TargetPlugin.ts
packages/repack/src/webpack/utils/env/__tests__/getDevServerOptions.test.ts
packages/repack/src/webpack/utils/env/getDevServerOptions.ts

fix: windows support fix in TargetPlugin for HMRClient && remove default 'localhost' in getDevServerOptions for windows
HMR is not working on windows due to the incorrect regexp in `webpack.NormalModuleReplacementPlugin`.
Besides, the fallback value for `host` in `getDevServerOptions` should be removed to allow access for DevServer by IP in LAN.

fix: windows support fix in HMR

---

packages/TesterApp/index.js
packages/repack/src/client/chunks-api/ChunkManager.ts

Caching chunks in development environment was causing issues related to not refreshed chunk content after app reload. This PR resolves it by refetching chunks every time in dev env.

fix: stop caching chunks in dev environment

---

packages/repack/src/webpack/plugins/AssetsResolverPlugin/AssetResolver.ts

Fixes #97 
Fix `AssetResolver` to use correct regex for matching scales. Otherwise it will fail if there are missing scales - e.g. only `3x`.
1. Rename image to `@3x` scale.
2. Run development server in TesterApp.
3. Request the bundle.

fix: asset resolver failure due to missing scales

---

packages/dashboard/src/pages/ServerLogs/ServerLogs.tsx

Use actual count of server logs in _Showing last <COUNT> logs._ label in the dashboard.

feat: show actual server logs count

---

packages/repack/commands.js

- Fixes #105 
1. Run Re.Pack's start/bundle in TesterApp (it should not crash)
1. Change `webpack.config.js` to `webpack2.config.js`
1. Run Re.Pack's start/bundle in TesterApp (it should crash)
1. Run Re.Pack's start/bundle in TesterApp with `--webpackConfig ./webpack2.config.js` (it should not crash)

fix: prevent crash when using custom Webpack path

---

packages/repack/ios/ChunkConfig.m

On iOS loading async chunks in release mode would always fail due to the chunk config always saying it is an absolute URL. This PR fixes the `fromConfigDictionary` method to correctly handle type conversion.  
Build a release build of the iOS TesterApp and see it never loading the async chunk before this change, but that the thing works fine with my change. Make sure you are not loading main bundle from network!

fix: pointer to bool conversion in chunk config on iOS

---

packages/repack/android/src/main/java/com/callstack/repack/FileSystemChunkLoader.kt
packages/repack/src/client/api/ChunkManagerBackend.ts
packages/repack/src/client/api/__tests__/ChunkManagerBackend.spec.ts

Fix setting absolute flag and resolving promise inside the file system chunk loader
Add tests for absolute equals`true`.

fix: absolute flag and promise resolving inside the file system chunk loader

---

packages/TesterApp/ios/Podfile.lock
packages/repack/src/client/setup/modules/WebpackHMRClient.ts
packages/repack/src/runtime-globals.d.ts
packages/repack/src/webpack/plugins/DevServerPlugin/DevServerPlugin.ts

In some cases, value returned by process.env.__PUBLIC_PORT__ was undefined because of which hot reload wasn't working.
Fixes https://github.com/callstack/repack/issues/141
Make sure that hot reload is working as expected.

fix: replace process.env.__PUBLIC_PORT__ by __PUBLIC_PORT__

---

packages/repack/src/webpack/loaders/assetsLoader.ts

It fixes #148 .
Add two images and name it same way but one of them should have `@2x` suffix. On an iOS simulator image with mentioned suffix should be displayed.

fix: images with higher resolution not used when possible

---

packages/TesterApp/android/gradle/wrapper/gradle-wrapper.properties
packages/TesterApp/ios/File.swift
packages/TesterApp/ios/Podfile
packages/TesterApp/ios/Podfile.lock
packages/TesterApp/ios/TesterApp.xcodeproj/project.pbxproj

This PR adds support for M1 mac architecture to the TesterApp 
Tester App works as expected

chore: make tester app compatible with M1 mac

---

packages/repack/src/webpack/loaders/assetsLoader.ts

It fixes parsing scale because when scale was i.e `3.5` then asset was not properly resolved.
Thanks for the really good catch  👍 https://github.com/callstack/repack/pull/153#discussion_r798273941
1. Add 2 images and name one of them with i.e: @3.5x suffix
2. Image that has the most suitable scale should be used 
(i.e screen's `PixelRatio` is equal to 4 and we've added two images with `@2x` and `@3.5x`. Image that scale is equal to `3.5` will be used)

fix: use parse float instead of parse int for scale

---

packages/repack/src/server/compilerWorker.ts

In this PR we provide support for `watchOptions`
https://webpack.js.org/configuration/watch/#watchoptions
It closes #137.
1. Add watchOptions to the webpack's config file
2. Specify which file webpack's should ignore
3. Changes in the specified file should be ignored by the webpack's compiler

fix: pass watch options to the compiler worker

---

packages/TesterApp/src/App.js
packages/TesterApp/webpack.config.js
templates/webpack.config.js

In this PR including any comments to the minified bundle has been disabled.
It fixes #128
JSC engine should return correct column number when we've thrown error.

fix: wrong error position on JSC engine

---

packages/repack/src/webpack/loaders/assetsLoader.ts

We use `parseFloat` instead of `parseInt` for scale keys as well as for scale numbers.
It fixes #157.
1. Add images with suffixes that contain same number before decimal point with different decimal places.
2. Image with the most suitable scale for the screen should be used

fix: use parse float for scale keys instead of parse int

---

packages/repack/src/webpack/plugins/OutputPlugin.ts

In `ChunkManagerBackend`,  params `chunkId`  is a string.
But chunkId in `__CHUNKS__` is a number.

Fix a bug in loading local chunks

---

packages/dashboard/package.json
packages/dashboard/yarn.lock
packages/repack/src/webpack/plugins/OutputPlugin.ts
yarn.lock

Add extra entry chunk identification to prevent incorrect bundle output when including splitchunk in webpack.config.js.
And add cross-env to dashboard for better development experiences on windows.
run the TeseterApp and it'll output the same bundle as before

fix: add extra entry chunk identification

---

packages/dev-server/src/plugins/wss/servers/HermesInspectorProxy.ts

Silence `/json` endpoint logging to avoid cluttering console output when debugging with Hermes.

feat(dev-server): silence json endpoint logging

---

.changeset/pre.json
.changeset/red-garlics-perform.md
packages/TesterApp/package.json
packages/repack/CHANGELOG.md
packages/repack/package.json
packages/repack/src/webpack/plugins/RepackPlugin.ts
packages/repack/src/webpack/plugins/RepackTargetPlugin/RepackTargetPlugin.ts
packages/repack/src/webpack/plugins/RepackTargetPlugin/runtime/RepackInitRuntimeModule.ts
packages/repack/src/webpack/plugins/RepackTargetPlugin/runtime/implementation/init.ts
yarn.lock

Upgrades `@pmmmwh/react-refresh-webpack-plugin` and adds `react-refresh@^0.14.0` as a `@callstack/repack` dependency.
- HMR/FR works in TesterApp

feat(repack): upgrade React Refresh Webpack Plugin

---

.changeset/angry-horses-poke.md
.changeset/itchy-dryers-sparkle.md
.changeset/pre.json
packages/TesterApp/package.json
packages/dev-server/CHANGELOG.md
packages/dev-server/package.json
packages/dev-server/src/createServer.ts
packages/dev-server/src/plugins/api/apiPlugin.ts
packages/dev-server/src/plugins/api/index.ts
packages/dev-server/src/plugins/wss/servers/WebSocketApiServer.ts
packages/dev-server/src/plugins/wss/wssPlugin.ts
packages/dev-server/src/types.ts
packages/repack/CHANGELOG.md
packages/repack/package.json
packages/repack/src/commands/start.ts
packages/repack/src/webpack/Compiler.ts
yarn.lock

- Adds API to `@callstack/repack-dev-server` with Webpack-based implementation to `@callstack/repack`.

feat(dev-server, repack): add dev server API

---

packages/TesterApp/webpack.config.mjs
templates/webpack.config.cjs
templates/webpack.config.mjs
website/docs/code-splitting/code-push.md
website/docs/code-splitting/glossary.md
website/docs/code-splitting/guide-async-chunks.md
website/docs/code-splitting/local-vs-remote-chunks.md
website/docs/code-splitting/usage.md
website/package.json
website/sidebars.js
website/static/diffs/repack_v2-v3.diff

- Unify output paths in Webpack config
- Add Local vs Remote chunks guide
No changeset is necessary.

feat(repack): unify output paths in Webpack configs and add local chunks docs

---

packages/repack/babel.config.js

`@callstack/repack/client`'s code should not be transformed more that it's necessary and it it should retain ESM import and exports - this is necessary so that Webpack can do tree shaking and esbuild-loader/swc-loader can properly transpile the code.
This is an implementation detail and should not affect users in any way - no changeset is necessary.

fix(repack): disable CJS tranform for client's code

---

.changeset/wet-tigers-deliver.md
packages/dev-server/src/createServer.ts

Prevent server logger from emitting log to API WS server before WS servers are created.
Run dev server - it should not crash.

fix(dev-server): prevent logger from sending to non-existent API WS server

---

.changeset/strange-shirts-guess.md
packages/repack/src/modules/ScriptManager/federated.ts

Prevent `importModule` from crashing with `cannot read property __isInitialized of undefined`.

fix: prevent importModule from crashing

---

.changeset/sweet-pets-scream.md
packages/repack/src/modules/ScriptManager/ScriptManager.ts
packages/repack/src/webpack/federated.ts
packages/repack/src/webpack/plugins/ManifestPlugin.ts
packages/repack/src/webpack/plugins/ModuleFederationPlugin.ts
packages/repack/src/webpack/plugins/__tests__/ModuleFederationPlugin.test.ts
packages/repack/src/webpack/plugins/index.ts
website/docs/module-federation.md

Adds custom `ModuleFederationPlugin` to abstract platform (React Native) differences.
Related #199 
- `module-federation` example should work: https://github.com/callstack/repack-examples/tree/repack-module-federation-plugin

feat(repack): add ModuleFederationPlugin with @ support

---

.changeset/gentle-jeans-film.md
packages/repack/src/webpack/Compiler.ts

Those changes will allow `Worker` to access process envs from parent (by passing `SHARE_ENV` symbol). This way passing `STANDALONE=1 yarn start` will expose STANDALONE process env and it will be accessible in `webpack.config` at project level

fix: prevent removing envs

---

.changeset/brown-jokes-remain.md
packages/repack/commands.js
packages/repack/src/commands/start.ts
packages/repack/src/types.ts

When working with `repack-examples` on Android there the error `[ScriptManager] Failed to load script: [NetworkFailure] ...` occured when an attempt to load scripts from remote dev servers runs on different port that host app. It's because those remote ports are not reversed when ScriptManager tries to resolve from `localhost`. Logic to reverse ports is implemented on `watchRun` which seems to be 'too' late to prevent mentioned crash.
This PR expose `--reverse-port` flag which allow to reverse port upfront when starting dev server.

fix: expose port reverse argument

---

.changeset/chilled-oranges-leave.md
packages/repack/src/commands/bundle.ts

Exit with non-zero exit code if compilation has errors
-  [x] CI

fix: Exit with non-zero exit code if compilation has errors

---

templates/webpack.config.cjs

This fixes a typo in `templates/webpack.config.cjs` which causes webpack to not work/crash.  It changes `dirname` to `__dirname`.

fix: typo in dirname in templates/webpack.config.cjs fix

---

packages/debugger-app/index.js

use fileURLToPath function to get path of URL instead of .pathname (added in [v10.12.0](https://nodejs.org/dist/latest-v10.x/docs/api/url.html#url_url_fileurltopath_url))
fixes #219

fix(debugger-app): use `fileURLToPath` to get path of url

---

.changeset/tricky-papayas-perform.md
packages/repack/src/modules/ScriptManager/ScriptManager.ts
packages/repack/src/modules/ScriptManager/__tests__/ScriptManager.test.ts

This fix detects missing React Native module (e.g. due to missing `pod install` after installation) and raises error if true.
This change improves developer experience. Should not affect any other areas.
Done a simple test on TesterApp and seems that nothing is broken by this change.
1. Setup a RN application
2. Install `repack` without updating native dependencies
3. Setup Module Federation in app and use it
4. New error `repack react-native module was not found` should appear instead of instead of `[ScriptManager] Failed to load script`

feat: Raise error on missing native module

---

.changeset/loud-seas-drum.md
packages/repack/commands.js
packages/repack/package.json
packages/repack/src/commands/bundle.ts
packages/repack/src/types.ts
packages/repack/src/webpack/plugins/LoggerPlugin.ts
yarn.lock

Allows creating JSON files of compilation stats that can be analyzed with https://statoscope.tech/
Command-line argumes take precedence over options in `webpack.config.js`
Copied behavior from webpack-cli: https://github.com/webpack/webpack-cli/blob/26ba6a82e7bc596e7fe48db9028f79e65e8131bc/packages/webpack-cli/src/webpack-cli.ts#L2291-L2299 
<details>
<summary>Based on this local patch</summary>
```diff
diff --git a/node_modules/@klapp/native/node_modules/@callstack/repack/commands.js b/node_modules/@klapp/native/node_modules/@callstack/repack/commands.js
index 8342509..b045590 100644
--- a/node_modules/@klapp/native/node_modules/@callstack/repack/commands.js
+++ b/node_modules/@klapp/native/node_modules/@callstack/repack/commands.js
@@ -65,7 +65,16 @@ module.exports = [
name: …
```

feat: Allow storing compilation stats in file

---

.changeset/ten-tigers-kiss.md
packages/repack/src/webpack/Compiler.ts
packages/repack/src/webpack/utils/adaptFilenameToPlatform.ts
packages/repack/src/webpack/utils/index.ts

This PR slightly refactors what was already implemented by @meypod in #256 – instead of duplicating each asset under a key which is valid pathname for Windows I'm modifying (or not) the filename based on the platform in context of which `Complier` is run. This should be safe as it will not affect production builds because the `Compiler` in only used with devServer.
Unfortunately I don't have access to a machine running Windows – @meypod would you be able to test that change and let me know if it's working properly on your end?

refactor(webpack/Compiler): remove duplicated assets in assetCache

---

website/docs/code-splitting/usage.md
website/versioned_docs/version-2x/code-splitting/usage.md

Updated TesterApp urls in Code Splitting  v3 and v2 docs - old urls threw 404
n/a

docs: update old TesterApp urls for code splitting

---

packages/debugger-app/CHANGELOG.md
packages/debugger-app/package.json

I forgot to release `debugger-app` package when releasing repack `3.0.1` version. It includes one fix for Windows platform: https://github.com/callstack/repack/pull/255

chore: Relase 1.0.1 version of debugger-app package

---

README.md

Link to example config is not working.
Changed the link(s) to point to the new template files

Small fix to config example link in readme

---

.changeset/hungry-ligers-reflect.md
packages/repack/src/webpack/plugins/RepackPlugin.ts

This PR ensures the `entryName` optional config value is passed from `RepackPlugin` to the `OutputPlugin`. This fixes #258

fix: Pass entryName config from RepackPlugin to OutputPlugin

---

.changeset/six-falcons-heal.md
packages/repack/android/gradle.properties

In clean RN project created using CLI (RN version – 0.71.1) there was an error while build Android app. More context can be found in this issue: #291. Upgrading kotlin-gradle-plugin version specified in Repack solves that issue without the need to manually specify kotlin-gradle-plugin version override in the repack consumers their codebases. 
Tested in latest RN version (0.71.1) and a reasonably old one – 0.67.5 – in both cases clean RN app configured to be built using repack is working fine (in both debug and release).

chore(repack): Update kotlin-gradle-plugin version

---

.changeset/gold-cows-raise.md
packages/repack/src/modules/ScriptManager/Script.ts
packages/repack/src/modules/ScriptManager/ScriptManager.ts
packages/repack/src/modules/ScriptManager/__tests__/ScriptManager.test.ts
packages/repack/src/modules/ScriptManager/types.ts

Repack provides a way to implement OTA updates out-of-the-box.
Since `ScriptManager` has `prefetchScript` and `loadScript` methods which use `resolveScript` under the hood, there is a possible way to add a point between resolving script and loading it. In this point user could control the way Repack updates the script (fetch from network or use cached one).
This PR introduces new callback, that could be passed into so called locator or a kind of config in `addResolver` callback function return statement.
```
shouldUpdateScript?: (
scriptId?: string,
caller?: string,
isScriptCacheOutdated?: boolean
) => Promise<boolean> | boolean;
```
it is worth to mention that all the changes are optional, so nothing will be broken if user will not provide new callback and will do no changes at all. …

feat: over-the-air updates

---

.changeset/fresh-pandas-lie.md
packages/repack/src/webpack/plugins/DevelopmentPlugin.ts

close #251 
After the 0.5.x version of `@pmmmwh/react-refresh-webpack-plugin`, it inserts RefreshEntry into webpack by `EntryPlugin` instead of `compiler.options.entry`. Therefore, our current method cannot find the RefreshEntry entry file from `compiler.options.entry` and then adjust its order.
This merge is to fix this problem, a entry file added by EntryPlugin will end up stored in`compilation.globalEntry.dependencies`, we just need to move it to `compiler.options.entry`.

fix(reapck): compatible with @pmmmwh/react-refresh-webpack-plugin@0.5.x

---

.changeset/clean-queens-collect.md
packages/TesterApp/package.json
packages/TesterApp/webpack.config.mjs
packages/dashboard/package.json
packages/dashboard/webpack.config.js
packages/debugger-app/package.json
packages/debugger-app/webpack.config.cjs
packages/dev-server/package.json
packages/repack/package.json
templates/webpack.config.cjs
templates/webpack.config.mjs
yarn.lock

When using node v18 there is an error related to outdated hashing function being used by `webpack`:
```
Error: error:0308010C:digital envelope routines::unsupported
at new Hash (node:internal/crypto/hash:71:19)
at Object.createHash (node:crypto:133:10)
at BulkUpdateDecorator.hashFactory (/Users/jbroma/repack/main/node_modules/webpack/lib/util/createHash.js:145:18)
at BulkUpdateDecorator.update (/Users/jbroma/repack/main/node_modules/webpack/lib/util/createHash.js:46:50)
at OriginalSource.updateHash (/Users/jbroma/repack/main/node_modules/webpack-sources/lib/OriginalSource.js:138:8)
at NormalModule._initBuildHash (/Users/jbroma/repack/main/node_modules/webpack/lib/NormalModule.js:880:17)
at handleParseResult (/Users/jbroma/repack/main/node_modules/webpack/lib/NormalModule.js:946:10)
at …
```

chore: node v18 compatibility

---

website/docs/getting-started.mdx

Newer versions of RN set `bundleCommand` in  a different place in`build.gradle`. This documentation change aims to update information on where it should be placed.

Update "Configure Android" section

---

.changeset/funny-clocks-play.md
packages/repack/android/src/main/java/com/callstack/repack/ChunkConfig.kt
packages/repack/src/modules/ScriptManager/Script.ts
packages/repack/src/modules/ScriptManager/__tests__/ScriptManager.test.ts

Fix for the case where native `ScriptConfig` object on Android was causing a crash because of missing key in `ReadableMap`

fix(repack): verifyScriptSignature defaults to false

---

.changeset/cool-otters-wash.md
packages/repack/src/webpack/plugins/CodeSigningPlugin.ts
packages/repack/src/webpack/plugins/__tests__/CodeSigningPlugin.test.ts

Due to reports of hashes not matching in some projects, the execution of the CodeSigningPlugin was moved to a later stage of compilation. Instead of hooking into `processAssets` hook, we now tap into `afterProcessAssets` hook, which should ensure that we generate the mapping file out of fully processed chunks.
- UI tests

fix(repack): move code-signing plugin execution to a later stage

---

.changeset/honest-glasses-yell.md
packages/repack/src/webpack/loaders/assetsLoader/__tests__/assetsLoader.test.ts
packages/repack/src/webpack/loaders/assetsLoader/inlineAssets.ts

Added automatic scale resolution for inlined assets. This change only affects scaled inlined assets. 
This resolves an issue where an unstyled `Image` with inlined source was not being displayed (the width & height won't be picked up properly unless it's a single `URISource`
Result of inlining scaled asset before:
```ts
[
{
uri: 'data:image/png;base64,...',
scale: 1,
width: 10,
height: 10,
},
{
uri: 'data:image/png;base64,...',
scale: 2,
width: 10,
height: 10,
},
]
```
Result of inlining scaled asset after:
```ts
{
uri: 'data:image/png;base64,...',
scale: 2,   // only the matching scale gets picked up
width: 10,
height: 10,
},
```
- UI tests

feat(repack): resolve scale automatically for inlined assets

---

.changeset/famous-clouds-sparkle.md
packages/TesterApp/index.js
packages/TesterApp/package.json
packages/TesterApp/webpack.config.mjs

This PR improves how remote assets and bundles are served in the TesterApp.
After running `yarn serve-remote-assets` a simple server will be started, providing both remote assets and remote bundles. This will help test the release version of the TesterApp for which DevServer is not started and we need to serve remote bundles manually.
Follow these steps while being in the TesterApp directory:
- yarn bundle
- yarn server-remote-assets
- build the app in the Release scheme/variant
- Remote Chunks and mini-apps as well as Remote Assets should work

chore(TesterApp): Improve remote assets and bundles serving for TesterApp

---

.changeset/fluffy-flies-tell.md
packages/repack/src/webpack/plugins/utils/AssetsCopyProcessor.ts

Temporary workaround for the OutputPlugin's `assetsCopyProcessor` to fix the issue where the whole plugin would fail because of chunks that have no files associated with them.

fix: skip chunks that have no files associated with them

---

.changeset/blue-carrots-collect.md
packages/repack/android/src/main/java/com/callstack/repack/ChunkConfig.kt
packages/repack/android/src/main/java/com/callstack/repack/CodeSigningUtils.kt
packages/repack/android/src/main/java/com/callstack/repack/RemoteChunkLoader.kt
packages/repack/ios/CodeSigningUtils.swift
packages/repack/ios/ScriptConfig.h
packages/repack/ios/ScriptConfig.m
packages/repack/ios/ScriptManager.mm
packages/repack/src/modules/ScriptManager/Script.ts
packages/repack/src/modules/ScriptManager/__tests__/ScriptManager.test.ts
packages/repack/src/modules/ScriptManager/federated.ts
packages/repack/src/modules/ScriptManager/types.ts
packages/repack/src/webpack/plugins/CodeSigningPlugin.ts
packages/repack/src/webpack/plugins/__tests__/CodeSigningPlugin.test.ts
packages/repack/src/webpack/plugins/__tests__/__fixtures__/example.chunk.bundle
packages/repack/src/webpack/plugins/__tests__/__fixtures__/example.container.bundle
packages/repack/src/webpack/plugins/__tests__/__fixtures__/local.chunk.bundle
packages/repack/src/webpack/plugins/__tests__/__fixtures__/main.bundle

This PR integrates the the tokens generated by `CodeSigningPlugin` to the bundles. This removes the need for matching the tokens with the bundles in the `ScriptManager` setup.
By embedding the tokens directly into the bundles we can eliminate the need of creating `tokenResolver` and fetching the tokens separately. After downloading the bundle, RePack will now evaluate whether the bundle is signed or not, extract the token and perform verification (if enabled). This solution comes with one tradeoff
The behaviour of `verifyScriptSignature` flag (as well as it's type) was changed. From now on, by default, the flag is set to `none`, which means no code-signature verification will take place. You can set the flag to one of the following string literals to control the verification process: …

feat: code-signing integrated tokens

---

packages/TesterApp/webpack.config.mjs
templates/webpack.config.cjs
templates/webpack.config.mjs
website/static/diffs/repack_v2-v3.diff

This PR addresses the issue of a too-broad regexp used in the webpack config templates – specifically `babel-loader` `include` array. The regexp at issue matched every package with a name starting with `react`. Merging this PR will prevent issues like #358. Unfortunately, since the template is not a part of Repack, this fix cannot be released and pulled by Repack users – everyone already using Repack would have to change the config manually.
For all new apps created using `repack-init`, this wouldn't be a problem since the script is using the latest version of the templates from the `main` branch.

fix: Replace too broad regexp in babel-loader config in webpack config templates

---

.changeset/polite-rockets-double.md
packages/init/src/tasks/handleReactNativeConfig.ts

Fixes bad package name in `handleReactNativeConfig.ts`.

fix(init): fix bad package name in handleReactNativeConfig

---

.github/workflows/deploy-pr.yml

When someone creates a PR from a fork, running a `Deploy Website` job will fail because it won't have access to secrets.
This change addresses that and won't waste time running a job that will eventually fail

fix: don't run preview docs CI job when source branch comes from a fork

---

.changeset/slow-knives-obey.md
packages/repack/android/build.gradle
packages/repack/android/src/main/AndroidManifest.xml

This is a change that'll be required starting from React Native 0.73.x. More context can be found here: https://github.com/react-native-community/discussions-and-proposals/issues/671

chore(repack): Add namespace to build.gradle for react-native 0.73+ compat

---

.changeset/slow-knives-obey.md
packages/repack/android/build.gradle
packages/repack/android/src/main/AndroidManifest.xml

This reverts commit 229c4f87d2b1ebaf6380717a6088b919f97586cf.
It turns out, at least for now, that this change is a breaking one. Let's revert it and see whether the support for reading `namespace` field from the build.gradle will get backported to older versions of react-native-cli or maybe we will need to release a new major version of the Repack targeting react-native 71+

Revert "chore(repack): Add namespace to build.gradle for react-native 0.73+ compat (#379)"

---

.changeset/sour-meals-cough.md
packages/repack/src/webpack/loaders/assetsLoader/__tests__/assetsLoader.test.ts
packages/repack/src/webpack/loaders/assetsLoader/convertToRemoteAssets.ts

Fixed an issue for remote-assets where only the basename from `publicPath` was included.
Example of the problem:
if `publicPath` was set to
```sh
http://localhost:9999/remote-assets
```
then final URL would look like this:
```sh
http://localhost:9999/assets/image.png
```
instead of
```sh
http://localhost:9999/remote-assets/assets/image.png
```

fix: remote-assets url includes full publicPath now

---

.github/workflows/deploy-pr.yml

Modified the condition in the `deploy-pr` workflow to allow for it to be run manually

chore: allow deploy-pr workflow to be run manually

---

.changeset/serious-cameras-move.md
packages/TesterApp/ios/Podfile.lock
packages/repack/callstack-repack.podspec

`JWTDecode` pod recently released new minor version of their library where they simply removed support for ios 12. Since we still want to support iOS 12, `.podspec` was modified to reflect what versions of the pod dependencies are needed for the project to work on iOS.
Closes https://github.com/callstack/repack/issues/389

fix: podspec fix

---

.changeset/loud-lemons-grin.md
packages/repack/android/build.gradle

Upgraded `com.nimbusds:nimbus-jose-jwt` to the newest version which is not listed as having security vulnerabilities
Tested locally on the super-app-showcase which utilises code-signing extensively

fix: update nimbus-jose-jwt android dependency

---

.changeset/beige-fireants-trade.md
packages/init/package.json
packages/init/src/tasks/addDependencies.ts
packages/init/src/tasks/checkPackageManager.ts
packages/init/src/tasks/checkReactNative.ts
packages/init/src/tasks/createWebpackConfig.ts
packages/init/src/tasks/modifyAndroid.ts
yarn.lock

- fixed an issue where repack-init would fail to use proper package manager in monorepo environment
- fixed an issue where react-native version had a semver range like `^0.71.3` instead of a plain version, which caused the whole repack-init to fail with an error: `Invalid Version: ^0.71.3`.
- updated function definition docs
executable tested locally

fix(repack-init): monorepo & version range support

---

.changeset/afraid-gorillas-fix.md
packages/repack/src/webpack/plugins/CodeSigningPlugin.ts
packages/repack/src/webpack/plugins/__tests__/CodeSigningPlugin.test.ts

Added `enabled` flag to `CodeSigningPlugin` to make it possible to disable the plugin when running in development environment. This flag defaults to `true` now to prevent a breaking change.
Added unit test for the flag

feat: add enabled flag to CodeSigningPlugin

---

.changeset/proud-coins-yell.md
packages/dev-server/package.json
yarn.lock

Upgraded `source-map` to `0.7.4`
Previous version was sometimes causing issues with `SourceMapConsumer` where it failed to initialize and therefore failed to symbolicate the stack trace.

chore(dev-server): upgrade source-map dependency

---

.changeset/sharp-penguins-worry.md
packages/repack/src/webpack/plugins/ModuleFederationPlugin.ts
packages/repack/src/webpack/plugins/__tests__/ModuleFederationPlugin.test.ts

**Problem Statement:**
In our current federated setup for React Native applications, a persistent issue emerged around the handling of shared dependencies, specifically with respect to deep imports from the 'react-native' library. These deep imports disrupted the efficient sharing of modules across federated boundaries. Furthermore, due to the challenges posed by these deep imports, our `assetsLoader` couldn't inline scaled assets in federated modules, leading to broken functionalities in some federated scenarios.
References:
[StackOverflow discussion on deep imports with Module Federation](https://stackoverflow.com/questions/65636979/wp5-module-federation-sharing-deep-imports)
[Webpack's resolveMatchedConfigs](https://github.com/webpack/webpack/blob/main/lib/sharing/resolveMatchedConfigs. …

feat(repack): builtin support for react-native deep imports for Module Federation

---

.changeset/fuzzy-panthers-brake.md
packages/repack/src/webpack/loaders/assetsLoader/__tests__/assetsLoader.test.ts
packages/repack/src/webpack/loaders/assetsLoader/inlineAssets.ts

**Fixed Asset Inlining for Newer React-Native Versions**
This PR addresses an issue with inlining assets in React-Native versions >= 0.72. The changes ensure that the `PixelRatio` import remains compatible with both older and newer versions of React-Native. We've added a check to determine if `PixelRatio` is an ESM module and adjust the import accordingly.
Changes:
- Updated logic in `inlineAssets.ts` to correctly import `PixelRatio` based on its module type.
- Enhanced code comments to provide clarity on the need for PixelRatio & AssetSourceResolver imports.
---
Note: For a more detailed understanding, refer to the changes in `.changeset/fuzzy-panthers-brake.md` and `inlineAssets.ts`.

fix(repack): fixed asset inlining for newer React Native versions

---

.changeset/grumpy-frogs-deliver.md
packages/init/package.json
packages/init/src/tasks/addDependencies.ts
packages/init/src/tasks/checkPackageManager.ts
yarn.lock

added support for bun as package manager for installing Re.Pack dependencies.

feat(init): support bun

---

.changeset/gold-bananas-think.md
packages/dev-server/src/plugins/devtools/devtoolsPlugin.ts

This PR fixes the `[DevServer] Failed to open stack frame in editor ` error.
This error occurs when attempting to open a file in an editor and using the dev tools plugin to get file info from the `request.body` by JSON.parse. However, the issue arises because the `request.body` is an object rather than a string, resulting in an error.
Here is an example of the request:
`curl 'http://localhost:8081/open-stack-frame' \
-X POST \
-H 'Connection: Keep-Alive' \
-H 'User-Agent: okhttp/4.9.2' \
-H 'Content-Type: application/json' \
--data-raw '{"file":"webpack:///node_modules/react-native/Libraries/LogBox/Data/LogBoxData.js","lineNumber":195}'`
To avoid this error, it's important to verify the type of `request.body` before attempting to parse it.

fix(dev-server): fix Failed to open stack frame in editor error

---

.changeset/khaki-otters-smile.md
packages/repack/src/webpack/plugins/LoggerPlugin.ts

This PR introduces a performance improvement for HMR in the `@callstack/repack` package.
- Modified `LoggerPlugin.ts` to improve performance. Specifically, an update has been made to the `stats.toJson` method. By adding `all: false` we disable retrieving other stats that were being needlessly retrieved by default.
| Metric | Before Change (ms) | After Change (ms) |
|---|---|---|
| Min | 482 | 433 |
| Max | 616 | 549 |
| Mean | 528.62 | 476.60 |
| Standard Deviation | 60.29 | 29.16 |
| Metric | Before Change (ms) | After Change (ms) |
|---|---|---|
| Min | 40 | 0.1 |
| Max | 146 | 1 |
---

refactor(repack): improve HMR performance

---

.changeset/honest-coins-ring.md
packages/repack/src/webpack/plugins/ModuleFederationPlugin.ts

Spread operator used inside of Re.Pack's `ModuleFederationPlugin` was passing `reactNativeDeepImports`  as a prop to webpack's `ModuleFederationPlugin` and causing schema validation error. Now all props from `config` are passed explicitly.

fix(repack): fix webpack's ModuleFederationPlugin configuration

---

.changeset/stale-panthers-taste.md
packages/TesterApp/__tests__/start.test.ts
packages/TesterApp/__tests__/webpack.config.mjs
packages/TesterApp/package.json
packages/TesterApp/webpack.config.mjs
packages/repack/package.json
packages/repack/src/webpack/plugins/DevelopmentPlugin.ts
website/docs/configuration/guides/lazy-compilation.mdx
website/sidebars.js
yarn.lock

Enable experimental lazy compilation support. This is done via `react-native-event-source` package which serves as a polyfill for `EventSource` which is not present in `react-native` environment.

feat: experimental lazy-compilation support

---

.changeset/fast-geckos-wonder.md
.github/workflows/test.yml
CONTRIBUTING.md
packages/dev-server/babel.config.cjs
packages/dev-server/package.json
packages/init/package.json
packages/repack/babel.config.js
packages/repack/package.json
packages/repack/src/index.ts
packages/repack/src/shims.ts
website/docs/getting-started.mdx
yarn.lock

**Update Minimum Node Version to 18**
Given that Node v16 reached its End of Life (EOL) on September 11, 2023, this pull request updates various parts of our codebase to set the minimum supported Node version to 18.
**Details of the Changes:**
1. **GitHub Actions Workflow Update**:
- Removed Node v16 from our testing matrix in `.github/workflows/test.yml`.
2. **Documentation Update**:
- Updated the minimum recommended Node version in `CONTRIBUTING.md`.
3. **Codebase Updates**:
- Updated the Babel config target version for both `packages/dev-server/babel.config.cjs` and `packages/repack/babel.config.js`.
- Adjusted the "engines" field in `package.json` for `packages/dev-server`, `packages/init`, and `packages/repack` to reflect the new minimum Node version.
- Updated the Node types version …

[BREAKING] chore: update minimum node version to 18

---

packages/TesterApp/webpack.config.mjs
templates/webpack.config.cjs
templates/webpack.config.mjs

When using expo library or when using expo and repack,
Need to modify it to `expo` instead of `@expo` to work.
Can refer to this [comment](https://github.com/callstack/repack/issues/304#issuecomment-1809708696).

fix: `@expo` changed to `expo` in babel-loader config in webpack config templates

---

.changeset/serious-hairs-thank.md
packages/TesterApp/webpack.config.mjs
packages/repack/src/commands/bundle.ts

See https://webpack.js.org/api/node/#run
> Don't forget to close the compiler, so that low-priority work (like persistent caching) have the opportunity to complete.
```sh
turbo run build && yarn workspace testerapp run bundle:ios
webpack 5.75.0 compiled successfully in 14680 ms 
webpack 5.75.0 compiled successfully in 1000 ms
```

fix: make webpack cache work

---

.changeset/warm-numbers-doubt.md
packages/TesterApp/ios/Podfile.lock
packages/TesterApp/ios/TesterApp.xcodeproj/project.pbxproj
packages/TesterApp/package.json
packages/repack/android/build.gradle
packages/repack/android/src/main/java/com/callstack/repack/ChunkManagerModule.kt
packages/repack/android/src/main/java/com/callstack/repack/ChunkManagerPackage.kt
packages/repack/android/src/newarch/ScriptManagerSpec.kt
packages/repack/android/src/oldarch/ScriptManagerSpec.kt
packages/repack/callstack-repack.podspec
packages/repack/ios/ScriptManager.h
packages/repack/ios/ScriptManager.mm
packages/repack/package.json
packages/repack/src/modules/ScriptManager/NativeScriptManager.ts
packages/repack/src/modules/ScriptManager/ScriptManager.ts
packages/repack/src/modules/ScriptManager/__tests__/ScriptManager.test.ts
yarn.lock

This PR aims to add a turbo module with backward compatibility. Re.Pack current implementation directly uses RN native modules, but with this change, there is a `SPEC` implementation that allows for more efficient communication between native and JavaScript. This change allows for both old and new architecture. All implementation follows the official react native bob builder template. 
- Make sure you are currently using the newArch and the setup conforms to [React Native Doc directives](https://reactnative.dev/docs/next/new-architecture-app-intro) which also means you're on **`RN>=0.68.0`**
NOTE: TesterApp currently meets this requirement if you're using repack TesterApp.
- You will only need to update your `android/gradle.properties` file as follows:
**`newArchEnabled=true`**
-  and …

New arch migration

---

.changeset/dry-trains-join.md
packages/repack/src/webpack/plugins/RepackTargetPlugin/RepackTargetPlugin.ts

When using `pnpm` or `yarn` with `pnpm` linker, the path to `react-native` can be different:
`react-native-virtual-38652004f3/package/Libraries/Utilities/HMRClient.js`
`react-native@0.71.8_@babel+core@7.23.0_@babel+preset-env@7.22.20_react@18.2.0/node_modules/react-native/Libraries/Utilities/HMRClient.js`
This change allows to match these additional cases as well and include `DevServerClient` from 'Re.Pack' properly.
Pretty sure we don't need to make it any more stricter than this, the chance of collision with something else is close to 0

fix: support non-classic paths to HMRClient from react-native

---

.github/workflows/close-stale.yml
.github/workflows/deploy-pr.yml
.github/workflows/deploy.yml
.github/workflows/test.yml

- Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-node@v3.
- For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

chore: Update actions to latest versions

---

packages/init/tsconfig.json

Modified `tsconfig.json` inside of `packages/init` to properly track imports within the package. 
This change is fully internal and does not require a new release of `@callstack/repack-init`
Thanks @Q1w1N for spotting this!
not needed

chore(init): proper TS setup

---

.changeset/shiny-planes-hope.md
packages/repack/src/webpack/plugins/OutputPlugin.ts
packages/repack/src/webpack/plugins/utils/AssetsCopyProcessor.ts
packages/repack/src/webpack/plugins/utils/__tests__/AssetsCopyProcessor.test.ts

Migrated `OutputPlugin` to run only inside of `done` hook - this enables usage of `OutputPlugin` with `rspack` as previous approach utilised features not available in `rspack` yet(?)

refactor(repack): use `done` hook inside of `OutputPlugin`

---

.npmrc
packages/TesterApp/webpack.config.mjs

makes workspace packages available in the virtual store
thanks to that, we can remove the weird fallback in `TesterApp` and avoid an issue where codegen will fail to find a package because it's symlinked to workspace and not present in the store.
n/a

chore: hoist workspace packages

---

packages/TesterApp/.gitignore
packages/TesterApp/android/app/src/main/java/com/testerapp/MainApplication.kt
packages/TesterApp/android/build.gradle
packages/TesterApp/android/gradle/wrapper/gradle-wrapper.properties
packages/TesterApp/android/gradlew
packages/TesterApp/android/gradlew.bat
packages/TesterApp/ios/Podfile
packages/TesterApp/ios/Podfile.lock
packages/TesterApp/ios/TesterApp.xcodeproj/project.pbxproj
packages/TesterApp/ios/TesterApp/AppDelegate.mm
packages/TesterApp/ios/TesterApp/Info.plist
packages/TesterApp/package.json
pnpm-lock.yaml

upgrade to `0.74-rc.6` to enable working on https://github.com/callstack/repack/issues/487

chore: upgrade tester app to react-native 0.74

---

.changeset/kind-scissors-kick.md
metro-compat-test/jest.setup.js
metro-compat-test/resolver/resolve.ts
package.json
packages/repack/src/webpack/utils/getResolveOptions.ts

BREAKING CHANGE:
`getResolveOptions` is now way more compatible with `metro-resolver` and `@react-native/metro-config`
1. `getResolveOptions` now accepts a second optional parameter called options with the following properties:
- `enablePackageExports` - defaults to `false`
- `preferNativePlatform` - defaults to `true`
2. Order of extensions was changed to match the order from `@react-native/metro-config`.
3. Resolution via Package Exports (`exports` field in package.json) is now optional and disabled by default.
It can now be enabled via `getResolveOptions` options parameter. This change was introduced to match `metro` defaults.
4. Default `conditionNames` are now: `['require', 'import', 'react-native']` and match `@react-native/metro-config` defaults.
Implementation passes every …

[BREAKING] feat: make resolver preset follow Metro defaults closely

---

.changeset/early-radios-grow.md
packages/repack/src/webpack/plugins/OutputPlugin.ts

Closes #361
When supplied with empty object as entry, `OutputPlugin` would fail because we didn't allow for such scenario. Since this scenario is a valid webpack use case (documented [here](https://webpack.js.org/concepts/entry-points/#object-syntax)), the constraint of `entryChunk` being present was removed. 
This feature is especially useful when using `ModuleFederation` - if we only care about the federated container + chunks, then all of our entrypoints declarations come from the `ModuleFederationPlugin`.

feat: OutputPlugin support for empty object as entry

---

metro-compat-test/package.json

lack of version in `metro-compat-test` causes changesets prereleases to fail, added placeholder version to work around this issue. 
Reference: https://github.com/changesets/changesets/pull/847
n/a

chore: add version to metro-compat-test

---

packages/TesterApp/android/resolveNodePackage.gradle

When I was trying to run `TesterApp` on Windows I saw that paths to symlinked packages weren't resolve correctly, for some reason `.canonicalPath` on Windows doesn't resolve symlink. In this Pull Request I've replace `.canonicalPath` with workaround functions that seems to work on both platforms. 
1. Clone repository
3. Go to `packages/TesterApp`
4. Try running `pnpm android` on Windows

fix(TesterApp): resolving symlinks in `resolveNodePackage.gradle` on Windows

---

.changeset/modern-dryers-itch.md
packages/dev-server/src/plugins/favicon/faviconPlugin.ts

fix: windows favicon path

---

.changeset/sharp-stingrays-wave.md
packages/TesterApp/webpack.config.mjs
packages/repack/src/webpack/utils/getInitializationEntries.ts
templates/webpack.config.cjs
templates/webpack.config.mjs

closes #501 
Updated templates to address following issues:
n/a

chore: update `webpack.config` templates

---

.changeset/big-spiders-guess.md
packages/repack/callstack-repack.podspec
packages/repack/ios/ScriptManager.mm

copied what Expo does in their native modules, seems to do the trick when dealing with `use_frameworks!`, best we test it out in the field and potentially revert before stable release.
closes #498

fix: make iOS native module compatible with `use_frameworks!`

---

.changeset/fair-experts-wave.md
packages/repack/src/commands/start.ts
packages/repack/src/env.ts
packages/repack/src/types.ts
packages/repack/src/webpack/utils/__tests__/getWebpackEnvOptions.test.ts
packages/repack/src/webpack/utils/getWebpackEnvOptions.ts

- RN CLI defaults to `''` as a default hostname.
- Fastify treats `''` as `localhost` but doesn't inform the user that it's listening on both interfaces at once.
Using a defined default allows for displaying both interfaces when starting the server:
```
ℹ [11:38:23.495Z][DevServer] Server listening at http://[::1]:8081
ℹ [11:38:23.499Z][DevServer] Server listening at http://127.0.0.1:8081
```
n/a
cherry-picked from #508

feat: use `localhost` as defined default hostname for the dev-server

---

.changeset/fluffy-insects-prove.md
packages/repack/src/commands/start.ts

Last compilation stats can origin from any platform, and when a new client connects, it will look for a last HMR update. Last stats will provide it with the name of the file, but it might be from another platform, and it will cause the file to not be found. This in turn will cause a full app reload, which would restart this flow, and cause and infinite loop. This PR addresses this problem by using separate slots for last stats for each platform.
This unblocks #567

fix: keep track of last compilation stats by platform

---

.changeset/hmr-client-prove.md
packages/dev-server/src/plugins/wss/servers/WebSocketHMRServer.ts

- When more than two devices are connected, one Android and one iOS, the second connected device will never receive the hot update notification, because the second device is different from the first connected device during traversal, and the loop will be exited directly.  We should continue to traversal next device when the platform of current device is different from  target device.
- Fix delete device don't work when disconnected

fix(dev-server): should traversal all connected devices when sending event

---

.changeset/fluffy-moons-tie.md
packages/TesterApp/webpack.config.mjs
templates/webpack.config.cjs
templates/webpack.config.mjs

chore: update templates

---

.changeset/silent-tigers-kiss.md
packages/repack/src/webpack/plugins/ChunksToHermesBytecodePlugin/utils/composeSourceMaps.ts
packages/repack/src/webpack/plugins/__tests__/ChunksToHermesBytecodePlugin.test.ts

use `execa.node` to reuse the node version from env instead of calling `node` - this mitigates the issue where sometimes node can't be found when building through Xcode

fix: hermes plugin node version

---

packages/TesterApp/src/deprecatedRemoteDebugger/DeprecatedRemoteDebuggerContainer.tsx

conditionally require `NativeDevSettings` module for Remote Debugger so that it doesn't crash when running a prod build.
n/a

fix(TesterApp): don't load DevSettings native module in release builds

---

.changeset/config.json

we need to `useCalculatedVersion` when doing snapshot releases because Cocoapods can't cope with version set to `0.0.0`
n/a

chore: add snapshot config for changesets

---

packages/repack/.clang-format
packages/repack/package.json
pnpm-lock.yaml

added clang-format for formatting objc and cpp code in repack
format config comes from reanimated lib
n/a

chore: add clang-format

---

.changeset/proud-shrimps-share.md
packages/repack/android/CMakeLists.txt
packages/repack/android/build.gradle
packages/repack/android/gradle.properties

fix: native build config for Android

---

packages/TesterApp/package.json

the fix for this is present in the CLI but our RN version is using older version of CLI.
n/a

fix: use appId for launching android TesterApp

---

.changeset/yellow-deers-build.md
packages/repack/src/webpack/loaders/assetsLoader/__tests__/assetsLoader.test.ts
packages/repack/src/webpack/loaders/assetsLoader/assetsLoader.ts
packages/repack/src/webpack/loaders/assetsLoader/options.ts

Closes #625
This pull request adds a new field to the remote assets configuration, allowing the specification of both the path and filename for an asset. Will be reflected in generated URL in `AssetSourceResolver`
1. (optional) Ensure that minification in webpack.config is disabled to make the generated JS code easier to inspect.
2. Add the following option to the remote-assets section of your webpack.config.js file:
```
assetPath: ({
resourcePath,
resourceFilename,
resourceDirname,
resourceExtensionType 
}) => {
const randomHex = Math.random().toString(16).slice(2, 8)
return `${resourceDirname}/one-more-folder/${resourceFilename}-${randomHex}.${resourceExtensionType}`
},
```
3. Build bundle
4. Verify that the remote assets are located in the specified folder and that the filenames …

feat: add assetPath to remote assets config

---

website/src/4.x/docs/guides/remote-assets.md

Promised documentation for https://github.com/callstack/repack/pull/651

docs: add documentation for `assetPath` for remote assets

---

.changeset/fuzzy-lions-think.md
packages/repack/src/commands/start.ts

https://github.com/callstack/repack/issues/644
Some cases like "http://localhost:8081/ios/src_app2_tsx-node_modules_react-native-reanimated_src_reanimated2_sync_recursive.chunk.bundle" can't parse the platform and filename correctly.

fix: correctly parse platform from file URL

---

.changeset/blue-dolls-know.md
apps/tester-federation/app.json
apps/tester-federation/index.js
apps/tester-federation/ios/Podfile.lock
apps/tester-federation/package.json
apps/tester-federation/webpack.config.host-app.mjs
packages/repack/android/src/main/java/com/callstack/repack/RemoteScriptLoader.kt
packages/repack/ios/ScriptManager.mm
packages/repack/src/modules/ScriptManager/ScriptManager.ts
pnpm-lock.yaml

Closes #553
- fixed `invalidateScripts` behaviour when trying to invalidate all scripts (when passing undefined or `[]` as argument)
- fixed hang in native ScriptManager on iOS when trying to execute file that doesn't exist
- aligned Android errors to match iOS when executing the same flow

fix: bundle caching after invalidating scripts

---

.changeset/brown-needles-pull.md
packages/repack/android/src/main/java/com/callstack/repack/RemoteScriptLoader.kt
packages/repack/android/src/main/java/com/callstack/repack/ScriptConfig.kt
packages/repack/android/src/main/java/com/callstack/repack/ScriptManagerModule.kt
packages/repack/ios/ScriptConfig.h
packages/repack/ios/ScriptConfig.mm
packages/repack/ios/ScriptManager.mm
packages/repack/src/modules/ScriptManager/NativeScriptManager.ts
packages/repack/src/modules/ScriptManager/Script.ts
packages/repack/src/modules/ScriptManager/ScriptManager.ts
packages/repack/src/modules/ScriptManager/__tests__/ScriptManager.test.ts
packages/repack/src/modules/ScriptManager/types.ts

Closes #660 
To prevent naming collisions on the device filesystem we're now using `uniqueId` as a filename.
`Script.locator.uniqueId` is generated by prepending `caller` to the `scriptId`.
If the `caller` is unknown, then `uniqueId` is equal to the `scriptId`.
This PR changes the cache key from `v3` to `v4` so all previous cache won't be accessible with the next release that includes this PR

fix: bundle naming collisions when using device filesystem cache

---

.changeset/loud-hounds-clean.md
packages/repack/commands.js
packages/repack/src/commands/bundle.ts
packages/repack/src/commands/start.ts
packages/repack/src/types.ts
packages/repack/src/webpack/Compiler.ts
packages/repack/src/webpack/utils/getWebpackEnvOptions.ts
packages/repack/src/webpack/webpackWorker.ts
website/src/4.x/docs/cli-commands/bundle.md
website/src/4.x/docs/cli-commands/start.md

Aligned both CLI command options to match the ones defined in [@react-native/community-cli-plugin](https://github.com/facebook/react-native/tree/main/packages/community-cli-plugin/src/commands)
Closes #695 
Closes #690

fix: CLI commands alignment

---

.changeset/metal-kiwis-yell.md
packages/repack/src/modules/WebpackHMRClient.ts

Due to the changes introduced in PR [facebook/react-native#43992](https://github.com/facebook/react-native/pull/43992), the `LoadingView.js `file has been renamed to `DevLoadingView.js`.
When using React Native version 75.x.x in your project, you may encounter the following error:
`Error: Can't resolve 'react-native/Libraries/Utilities/LoadingView' in ...`
This is because the `LoadingView.js` file has been renamed and needs to be updated accordingly in your codebase.

fix: LoadingView import

---

.changeset/fuzzy-bags-walk.md
packages/repack/src/modules/WebpackHMRClient.ts
packages/repack/src/modules/runtime-globals.d.ts
packages/repack/src/webpack/plugins/DevelopmentPlugin.ts

fix: compile-time check for RN version

---

.changeset/friendly-melons-argue.md
packages/repack/src/commands/utils/getWebpackConfigPath.ts

Closes https://github.com/callstack/repack/issues/721
- tested the fix in the issue's repro on a Windows PC

fix: finding path to `webpack.config.mjs` on Windows

---

.github/workflows/test.yml

This reverts commit f00b23a2f7ec61ef31a6b2050b55a2194ccbc579.
Reverting since it's prevent CI from running on V5 branch

Revert "chore: dont run CI job when working on website (#608)"

---

.changeset/proud-ants-protect.md
packages/repack/ios/ScriptConfig.mm
packages/repack/ios/ScriptManager.mm

The query object return by ScriptManager's resolver will be encoded in Script.from().
But on iOS side, the query will be encoded again.
This pr will fix this behavior.

fix: query object been encoded again on iOS side

---

.changeset/loud-falcons-prove.md
packages/repack/ios/ScriptManager.mm

On iOS ,if download bundle was not successful, throw an error.

fix: throw an error when bundle download was unsuccessful on iOS

---

ARCHITECTURE.md
CONTRIBUTING.md
README.md
packages/dev-server/README.md
packages/init/README.md
packages/repack/README.md
packages/repack/package.json
packages/repack/src/commands/rspack/bundle.ts
packages/repack/src/commands/rspack/start.ts
packages/repack/src/commands/webpack/bundle.ts
packages/repack/src/commands/webpack/start.ts
templates/webpack.config.cjs
templates/webpack.config.mjs
templates_v5/rspack.config.cjs
templates_v5/rspack.config.mjs
templates_v5/webpack.config.cjs
templates_v5/webpack.config.mjs
website/src/public/configs/webpack.config

Aligning the wording for Rspack support. Also changed the React Native CLI to React Native Community CLI. There's still v5.x docs missing, but let's address that separately.

docs: align wording with Rspack support

---

.changeset/serious-falcons-burn.md
packages/repack/src/commands/common/__tests__/setupStatsWriter.test.ts
packages/repack/src/commands/common/setupStatsWriter.ts
packages/repack/src/commands/rspack/bundle.ts
packages/repack/src/commands/webpack/bundle.ts

- fix TODO in `setupStatsWriter`
- moved error handling to bundle command
- added unit tests for stats writer

feat: normalize filepath and ensure path exists for stats writing

---

.changeset/lucky-paws-shop.md
packages/repack/src/utils/getResolveOptions.ts

metro doesn't support import fields at all, aligning for compat.
if a user wants to allow for importsFields, they can do so through `resolve.importsFields` and restoring the default value of `['imports']`
n/a

fix: disable package imports by default

---

.changeset/fast-falcons-joke.md
apps/tester-app/rspack.config.mjs
apps/tester-federation/rspack.config.host-app.mjs
apps/tester-federation/rspack.config.mini-app.mjs
packages/repack/src/rules/flowTypedModulesLoadingRules.ts
packages/repack/src/rules/index.ts
packages/repack/src/rules/nodeModulesLoadingRules.ts
packages/repack/src/rules/reactNativeCodegenRules.ts
packages/repack/src/rules/reactNativeLoadingRules.ts
packages/repack/src/utils/index.ts
templates_v5/rspack.config.cjs
templates_v5/rspack.config.mjs

feat: handle stripping flow types from popular packages

---

.changeset/heavy-drinks-heal.md
packages/repack/src/rules/nodeModulesLoadingRules.ts

fix: handle cjs, mjs, mts, cts files in the nested rules

---

.changeset/tidy-eels-clean.md
packages/repack/src/modules/ScriptManager/NativeScriptManager.ts
packages/repack/src/modules/ScriptManager/Script.ts
packages/repack/src/modules/ScriptManager/ScriptManager.ts
packages/repack/src/modules/ScriptManager/__tests__/ScriptManager.test.ts
packages/repack/src/modules/ScriptManager/types.ts

This PR introduces two new properties, `retry` and `retryDelay`, to the `ScriptConfig` within the download method. These properties aim to improve the download process by handling network failures more robustly. 
- **`retry`**: Specifies the number of attempts to retry the download in case of failure.
- **`retryDelay`**: Defines the delay (in milliseconds) between each retry attempt.
This feature aims to minimize the impact of transient network failures and improve the reliability of downloads in unstable network conditions.

feat: Add `retry` and `retryDelay` Properties to Enhance Download Method Reliability

---

pnpm-lock.yaml
website/package.json
website/src/styles/index.css

chore: upgrade rspress to 1.33

---

.changeset/tricky-donuts-fly.md
packages/repack/src/modules/ScriptManager/ScriptManager.ts
packages/repack/src/modules/ScriptManager/__tests__/ScriptManager.test.ts

https://github.com/callstack/repack/issues/770
The root cause was where cache is saving, script Resolver should not save the cache, it should be saved after script loaded successfully.
I added a test for failing scenario which expected to The failed script doesn't save on cache and also if scriptLoader called again, expected in second time fetch property should be true too.

fix: don't cache failed script

---

.changeset/brown-countries-tickle.md
packages/repack/src/modules/ScriptManager/federated.ts
packages/repack/src/plugins/ModuleFederationPluginV1.ts
packages/repack/src/plugins/__tests__/ModuleFederationPluginV1.test.ts
packages/repack/src/plugins/__tests__/ModuleFederationPluginV2.test.ts

fix: allow for custom federated filename in MF1 Plugin

---

.changeset/big-wolves-tell.md
packages/repack/package.json

fix: peer dep config in repack package

---

.changeset/clever-timers-decide.md
apps/tester-federation-v2/package.json
apps/tester-federation/package.json
packages/repack/src/commands/options.ts
packages/repack/src/commands/rspack/bundle.ts
packages/repack/src/commands/rspack/start.ts
packages/repack/src/commands/types.ts
packages/repack/src/commands/webpack/bundle.ts
packages/repack/src/commands/webpack/start.ts

feat: add `--config` cli option to commands

---

.changeset/odd-cars-yawn.md
apps/tester-app/ios/Podfile.lock
apps/tester-federation-v2/ios/Podfile.lock
apps/tester-federation/ios/Podfile.lock
packages/repack/src/commands/rspack/start.ts
packages/repack/src/commands/webpack/start.ts

addressed the TODO in start commands for the verbose flag:
n/a

fix: verbose flag in start command

---

.changeset/bright-scissors-kiss.md
apps/tester-app/__tests__/start.test.ts
packages/repack/src/commands/common/__tests__/setupInteractions.test.ts
packages/repack/src/commands/common/setupInteractions.ts
packages/repack/src/commands/options.ts
packages/repack/src/commands/rspack/start.ts
packages/repack/src/commands/types.ts
packages/repack/src/commands/webpack/start.ts
packages/repack/src/logging/reporters/ConsoleReporter.ts
packages/repack/src/plugins/LoggerPlugin.ts

removed `--silent` flag since it's handling is problematic, and it's much easier to achieve the desired result through stream redirection in the shell i.e. 
```bash
npx react-native start > /dev/null
```
n/a

[BREAKING] refactor: remove `--silent` CLI flag

---

packages/repack/src/commands/rspack/bundle.ts
packages/repack/src/commands/rspack/start.ts
packages/repack/src/commands/webpack/Compiler.ts
packages/repack/src/commands/webpack/bundle.ts
packages/repack/src/commands/webpack/start.ts
packages/repack/src/plugins/LoggerPlugin.ts

refactor: unify handling of `--verbose` flag in both commands

---

.changeset/cold-apes-swim.md
apps/tester-app/rspack.config.mjs
apps/tester-app/webpack.config.mjs
apps/tester-federation-v2/rspack.config.host-app.mjs
apps/tester-federation-v2/rspack.config.mini-app.mjs
apps/tester-federation-v2/webpack.config.host-app.mjs
apps/tester-federation-v2/webpack.config.mini-app.mjs
packages/repack/android/src/main/java/com/callstack/repack/FileSystemScriptLoader.kt
packages/repack/android/src/main/java/com/callstack/repack/RemoteScriptLoader.kt
packages/repack/android/src/main/java/com/callstack/repack/ScriptConfig.kt
packages/repack/ios/ScriptConfig.h
packages/repack/ios/ScriptConfig.mm
packages/repack/ios/ScriptManager.mm
packages/repack/src/plugins/DevelopmentPlugin.ts
packages/repack/src/plugins/RepackPlugin.ts

Fix bad source-map matching in DevTools by aligning the following:
Before:
After:

fix: source-map matching in React Native DevTools

---

.changeset/honest-items-happen.md
packages/repack/src/plugins/ModuleFederationPluginV2.ts

fix: expose MF2 plugin config to external tooling

---

.changeset/slimy-dragons-swim.md
apps/tester-app/ios/Podfile.lock
packages/repack/src/rules/nodeModulesLoadingRules.ts
packages/repack/src/rules/reactNativeLoadingRules.ts

This PR fixes the discrepancy between Re.Pack default module transform rules and the official RN Babel preset. 
`swc` uses `classic` runtime transform, while RN babel preset uses `automatic` JSX transform so we need to declare `runtime: 'automatic'` explicitly for the node module rules.

fix: add transform react jsx automatic to node module rules

---

.changeset/cold-chefs-confess.md
apps/tester-app/package.json
apps/tester-federation-v2/package.json
apps/tester-federation/package.json
packages/init/src/tasks/addDependencies.ts
packages/repack/package.json
pnpm-lock.yaml

Closes #804 
`@rspack/react-refresh-plugin` is now included in Re.Pack instead of being a peer dependcy since it's used in both webpack and rspack variants
n/a

feat: include `@rspack/react-refresh-plugin` with Re.Pack

---

.changeset/rude-points-ring.md
packages/repack/src/loaders/assetsLoader/__tests__/assetsLoader.test.ts
packages/repack/src/loaders/assetsLoader/assetsLoader.ts
packages/repack/src/loaders/assetsLoader/convertToRemoteAssets.ts
packages/repack/src/loaders/assetsLoader/extractAssets.ts
packages/repack/src/loaders/assetsLoader/types.ts
packages/repack/src/loaders/assetsLoader/utils.ts

Align how size of an asset is obtained with the behaviour in metro. This also prevents erroring out if the default asset in group can't be established.

fix: obtain asset size from first asset in group

---

.changeset/smooth-zebras-hunt.md
packages/repack/src/rules/reactNativeCodegenRules.ts

fix: split ts & tsx rules in codegen & enable source maps

---

.changeset/thick-pillows-act.md
packages/plugin-reanimated/src/plugin.ts

Added warning from reanimated to ignored ones since it's not relevant in runtime and is only used in tests
n/a

chore: ignore the warning from setupTests in reanimated plugin

---

.changeset/healthy-dots-tap.md
packages/repack/src/plugins/ModuleFederationPluginV2.ts

This PR addresses the warnings produced by Module Federation v2 (MF2) regarding dynamic imports in the loadEsmEntry function. These warnings are not relevant in the React Native environment since the loadEntry logic is overridden through a hook.
n/a

fix: ignore the MF2 runtime warning

---

.changeset/smart-carrots-sneeze.md
packages/repack/src/commands/common/__tests__/setupInteractions.test.ts
packages/repack/src/commands/common/runAdbReverse.ts
packages/repack/src/commands/common/setupInteractions.ts
packages/repack/src/commands/options.ts
packages/repack/src/commands/rspack/Compiler.ts
packages/repack/src/commands/rspack/start.ts
packages/repack/src/commands/webpack/start.ts

I didn't want to introduce a breaking change in CLI options in this PR so for now we check if the platform is not `ios`. Separate PR will change the `--reverse-port` flag into `--no-reverse-port`

feat: `adb reverse` interaction & run `adb reverse` by default

---

.changeset/dull-ants-change.md
packages/repack/src/commands/options.ts
packages/repack/src/commands/rspack/start.ts
packages/repack/src/commands/webpack/start.ts

Since `adb reverse` will be now run by default, the CLI option of `--reverse-port` was reworked into `--no-reverse-port` to turn off the default behaviour
n/a

[BREAKING] feat: invert the `--reverse-port` CLI option

---

.changeset/tasty-dolls-lie.md
packages/repack/src/index.ts

Reverts callstack/repack#802
This change caused the need to include both `webpack` and `rspack` after initializing new project using `repack-init` and this is not desired

Revert "chore: export commands from package entrypoint"

---

.changeset/khaki-days-call.md
.changeset/odd-teachers-repeat.md
apps/tester-app/ios/Podfile.lock
apps/tester-app/package.json
apps/tester-federation-v2/ios/Podfile.lock
apps/tester-federation-v2/package.json
apps/tester-federation/ios/Podfile.lock
apps/tester-federation/package.json
packages/repack/src/commands/common/runAdbReverse.ts
packages/repack/src/commands/rspack/start.ts
packages/repack/src/commands/webpack/start.ts
pnpm-lock.yaml

When starting the dev server, wait for device (`adb wait-for-device`) before running `adb reverse`.
This also makes the ADB reverse more resilient by running reverse on all available devices (similar to how Expo does it)

feat: wait for device before adb reverse

---

.changeset/quiet-camels-design.md
packages/repack/src/modules/FederationRuntimePlugins/CorePlugin.ts
packages/repack/src/modules/FederationRuntimePlugins/ResolverPlugin.ts

This PR resolves the module resolution errors that caused the server to fail during startup. The issues stemmed from incorrect import paths for CorePlugin and ResolverPlugin, as well as the ScriptManager module.

fix: Module Resolution Errors for ScriptManager Imports

---

.changeset/quiet-camels-design.md
packages/repack/src/modules/FederationRuntimePlugins/CorePlugin.ts
packages/repack/src/modules/FederationRuntimePlugins/ResolverPlugin.ts

Reverts callstack/repack#833
reverting since this doesn't fix the problem

Revert "fix: Module Resolution Errors for ScriptManager Imports"

---

.changeset/lazy-comics-promise.md
packages/repack/src/modules/FederationRuntimePlugins/CorePlugin.ts
packages/repack/src/modules/FederationRuntimePlugins/ResolverPlugin.ts

Fix for the reverted changes: https://github.com/callstack/repack/pull/834

fix: ScriptManager import path in MF runtime plugins (CorePlugin & ResolverPlugin)

---

apps/tester-app/ios/Podfile.lock
apps/tester-federation-v2/android/gradle.properties
apps/tester-federation-v2/ios/Podfile
apps/tester-federation-v2/ios/Podfile.lock
apps/tester-federation/android/gradle.properties
apps/tester-federation/ios/Podfile
apps/tester-federation/ios/Podfile.lock

The iOS test apps were failing to build due to the following error:
`/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator18.1.sdk/usr/include/c++/v1/__memory/unique_ptr.h:64:19 Invalid application of 'sizeof' to an incomplete type 'facebook::react::JSExecutorFactory'
`
Only happened with: `bridgeless_enabled => false`.

fix: enable bridgeless mode to fix iOS test app build issues

---

.changeset/fifty-rockets-laugh.md
packages/repack/src/plugins/DevelopmentPlugin.ts

added missing `.apply(compiler)` for providing `reactRefreshUtils`
n/a

fix: refresh utils missing apply compiler in DevelopmentPlugin

---

.changeset/nervous-wasps-applaud.md
apps/tester-app/rspack.config.mjs
apps/tester-federation-v2/rspack.config.host-app.mjs
apps/tester-federation-v2/rspack.config.mini-app.mjs
apps/tester-federation/rspack.config.host-app.mjs
apps/tester-federation/rspack.config.mini-app.mjs
packages/repack/src/rules/nodeModulesLoadingRules.ts
packages/repack/src/rules/reactNativeLoadingRules.ts
templates_v5/rspack.config.cjs
templates_v5/rspack.config.mjs

added some missing configuration to `builtin:swc-loader` rules:
n/a

fix: missing swc config in RN & NM rules

---

website/src/5.x/api/loaders/flow-loader.md

docs: align how options look between loader api docs

---

.changeset/curvy-lamps-kneel.md
packages/repack/src/modules/FederationRuntimePlugins/CorePlugin.ts
packages/repack/src/plugins/ModuleFederationPluginV2.ts

If the library config is not set to `script`, MF2 will not handle 2nd level remotes correctly (as in remotes of remotes). This can be currently observed in the super app showcase where it fails to load `AccountScreen` inside of any of the MiniApps.
Setting library type to `script` results in `preloadAssets` flow being trigger, so to counter this I've added a noop handler inside `generatePreloadAssets` hook. This is not needed anyways since when this method is called the assets (chunks of the remote) are already loaded into the container variable in the global scope. Setting this to a noop avoids a flow which is tailored for the browser environment (with `document` object present)
This should most likely be fixed in MF2 core itself but the solution to a [similar …

fix: loading of 2nd level MF2 remotes

---

.changeset/tricky-keys-kneel.md
packages/repack/src/modules/ScriptManager/Script.ts

Simplifies comparison with cached data. Also does not 'precompute' it before doing the comparison, so expression terminates on first difference.
Not sure if it is a real problem as the code might be called infrequently. I was just bugged by the eager version.

perf: do 'lazy' comparison in 'checkIfCacheDataOutdated'

---

.changeset/unlucky-starfishes-thank.md
apps/tester-app/package.json
apps/tester-federation-v2/package.json
apps/tester-federation/package.json
packages/init/src/tasks/addDependencies.ts
packages/repack/package.json
packages/repack/src/plugins/BabelPlugin.ts
packages/repack/src/plugins/RepackPlugin.ts
packages/repack/src/plugins/index.ts
pnpm-lock.yaml
website/src/5.x/api/plugins/internal.md
website/src/5.x/docs/getting-started/quick-start.mdx

instead of installing `babel-loader` as a separate dependency, it is now marked as a dependency of Re.Pack so it can be available in all configurations. `BabelPlugin` ensures that it's available in all kinds of setups (like pnpm) where `babel-loader` might be needed as a direct dependency of a project. 
n/a

feat: ship with `babel-loader` as a dependency

---

.changeset/pink-pants-vanish.md
apps/tester-app/webpack.config.mjs
packages/repack/src/modules/ScriptManager/Script.ts
packages/repack/src/modules/ScriptManager/__tests__/ScriptManager.test.ts
packages/repack/src/modules/ScriptManager/federated.ts
packages/repack/src/modules/ScriptManager/getWebpackContext.ts
packages/repack/src/modules/ScriptManager/types.ts
packages/repack/src/plugins/RepackTargetPlugin/InitRuntimeModule.ts
packages/repack/src/plugins/RepackTargetPlugin/LoadScriptRuntimeModule.ts
packages/repack/src/plugins/RepackTargetPlugin/ModuleErrorHandlerRuntimeModule.ts
packages/repack/src/plugins/RepackTargetPlugin/RepackTargetPlugin.ts
packages/repack/src/plugins/RepackTargetPlugin/implementation/init.ts
packages/repack/src/plugins/RepackTargetPlugin/implementation/loadScript.ts
packages/repack/src/plugins/RepackTargetPlugin/implementation/moduleErrorHandler.ts
packages/repack/src/types/runtime-globals.d.ts

partial solution to #866
In some cases `loadScript` runtime module might not get injected into the bundle. Since all of the logic for Repack runtime lives there, it might cause undefined behaviour like failing to process EarlyJS errors or failure to initialise Repack global object. 
This PR separates the `loadScript` part into it's own runtime module, and makes `init` and `moduleErrorHandler` parts separate runtime modules.
Previously in Rspack there was no way to add runtime modules - we could only edit existing ones and we were forced to concatenate init & load script modules into one. This is no longer the case so we can split them into separate entities.
The types injected into the global scope were also reworked - now most types are hidden behind a `RepackRuntimeGlobals` namespace to …

fix: decouple init & module error handling from runtime module

---

.changeset/brown-lemons-fix.md
packages/init/src/tasks/addDependencies.ts

before the version of `@rspack/core` was locked at 1.0.3 to make source maps work, this was fixed long time ago upstream so there is no reason to keep it locked anymore.
n/a

fix: install latest version of rspack with init

---

.changeset/gorgeous-nails-watch.md
packages/repack/src/plugins/RepackTargetPlugin/RepackTargetPlugin.ts

Looking over the RN codebase I've found that `ReactNativePrivateInitializeCore` reexports `InitializeCore`. Inside commit history we can find [attempts at making this module a noop](https://github.com/facebook/react-native/commit/b14b34b232b4873137ea3f3c7a90f86b9013885a) but ultimately it was always reverted because of issues at metro. 
We're not using metro and this isn't an issue with webpack/rspack so no reason why not to try it, especially since this allows for inlining entrypoints for faster startup (before webpack bailed out of this optimization because `InitializeCore` was used in other places)

feat: enable inlining RN entrypoints

---

website/rspress.config.ts

to do not update it every year :D

chore(docs): get year in footer dynamically

---

website/src/4.x/docs/getting-started.mdx
website/src/5.x/docs/getting-started/quick-start.mdx

docs: mention installing cocoapods

---

.changeset/khaki-drinks-join.md
apps/tester-app/ios/Podfile.lock
apps/tester-app/rspack.config.mjs
apps/tester-federation-v2/ios/Podfile.lock
apps/tester-federation-v2/rspack.config.host-app.mjs
apps/tester-federation-v2/rspack.config.mini-app.mjs
apps/tester-federation/ios/Podfile.lock
apps/tester-federation/rspack.config.host-app.mjs
apps/tester-federation/rspack.config.mini-app.mjs
packages/repack/src/rules/nodeModulesLoadingRules.ts
packages/repack/src/rules/reactNativeLoadingRules.ts
templates_v5/rspack.config.cjs
templates_v5/rspack.config.mjs

before too many loose mode transformations were enabled, being not spec compliant with `@react-native/babel-preset` - now only the default ones are provided with the config - making the compiled code more strict and spec compliant.

fix: use specific swc assumptions instead of general loose mode

---

website/src/5.x/docs/features/code-splitting.md
website/src/5.x/docs/features/dev-server.md
website/src/5.x/docs/features/devtools.md
website/src/5.x/docs/features/flow-support.md
website/src/5.x/docs/features/module-federation.md
website/src/5.x/docs/features/module-resolution.md
website/src/5.x/docs/features/reanimated.md
website/src/5.x/docs/getting-started/bundlers.md
website/src/5.x/docs/getting-started/microfrontends.md
website/src/5.x/docs/guides/bundle-analysis.md
website/src/5.x/docs/guides/configuration.md
website/src/5.x/docs/guides/debugging.md
website/src/5.x/docs/migration-guides/expo.md
website/src/5.x/docs/migration-guides/metro.md
website/src/5.x/docs/resources/glossary.md

Docs are deployed but they're still empty for some of the pages. This Pull Requests adds a relevant warning which informs visitors what's the status.

docs: add a warning for non-migrated pages

---

.changeset/fast-frogs-hang.md
apps/tester-federation-v2/package.json
packages/repack/package.json
packages/repack/src/plugins/ModuleFederationPluginV2.ts
packages/repack/src/plugins/__tests__/ModuleFederationPluginV2.test.ts
pnpm-lock.yaml

Closes #854 
Fixes an issue where MF2 plugin would cause a dev server crash because it expected every warning to have `moduleDescriptor.name` present. This was fixed by verifying the structure of warning object beforehand. I've also added additional check for the same warning in `runtime-core` which was added in newer versions of MF2.

fix: ignore warning handler in MF2 plugin

---

.changeset/six-mugs-peel.md
packages/plugin-nativewind/README.md
packages/plugin-nativewind/package.json
packages/plugin-nativewind/src/plugin.ts

Added a check for dependencies that are required by NativeWind integration. The check can be disabled through `checkDependencies: false` flag passed inside plugin options.
On top of that:

feat: add nativewind dependencies check

---

.changeset/tasty-feet-refuse.md
apps/tester-app/rspack.config.mjs
packages/plugin-nativewind/src/loader.ts
packages/plugin-nativewind/src/plugin.ts

Introduces a new `cssToReactNativeRuntimeOptions` option (name suggestions are welcome) that forwards directly to `cssToReactNativeRuntime` allowing configurations like `inlineRem` and `selectorPrefix`

Add cssInterop options to the Nativewind plugin

---

.changeset/pretty-years-sit.md
packages/repack/package.json
packages/repack/src/plugins/ModuleFederationPluginV2.ts
packages/repack/src/plugins/__tests__/ModuleFederationPluginV2.test.ts
pnpm-lock.yaml

Adding a check in `ModuleFederationPluginV2` to validate that a container's name is a valid JavaScript identifier.
It fixes the following error:
```
✖ [11:12:29.747Z][DevServer]   × Library name base (mini-app) must be a valid identifier when using a var declaring library type. Either use a valid identifier (e. g. mini_app) or use a different library type (e. g. `type: 'global'`, which assign a property on the global scope instead of declaring a variable). Common configuration options that specific library names are 'output.library[.name]', 'entry.xyz.library[.name]', 'ModuleFederationPlugin.name' and 'ModuleFederationPlugin.library[.name]'.
{
reqId: 'req-2',
err: {
type: 'Error',
message: "  × Library name base (mini-app) must be a valid identifier when using a var declaring library …
```

fix: force container name to be a valid js identifier

---

.changeset/weak-birds-change.md
packages/plugin-expo-modules/README.md
packages/plugin-expo-modules/package.json
packages/plugin-expo-modules/src/index.ts
packages/plugin-expo-modules/src/plugin.ts
packages/plugin-expo-modules/tsconfig.build.json
packages/plugin-expo-modules/tsconfig.json
pnpm-lock.yaml

Added expo-modules plugin package that fills the gap for integrating expo-modules with Re.Pack - for now the plugin only defines the `EXPO_OS` env var in runtime which is normally set by `babel-preset-expo`.

feat: expo-modules plugin

---

.changeset/violet-keys-trade.md
packages/repack/src/commands/common/__tests__/loadConfig.test.ts
packages/repack/src/commands/common/loadConfig.ts
packages/repack/src/commands/rspack/Compiler.ts

`compiler.name` is already utilised by `zephyr-repack-plugin` so it makes to normalize this across the commands. This also opens up a possibility to make `platform` param in configs optional (or remove it altogether later on)

feat: normalise `compiler.name` to compilation target platform

---

.changeset/dirty-terms-burn.md
packages/repack/src/rules/flowTypedModulesLoadingRules.ts

Added `react-native-camera` and `react-native-view-shot` to flow libs inside `FLOW_TYPED_MODULES_LOADING_RULES`
n/a

feat: extend list of flow-typed modules

---

.changeset/honest-foxes-hope.md
packages/plugin-nativewind/package.json

The last version of `postcss-loader` is 8.1.1

fix: correct 'postcss-loader' peer dependency version

---

.changeset/big-singers-shop.md
packages/init/src/index.ts
packages/init/src/tasks/completeSetup.ts

When initing Re.Pack in an existing project it doesn't make sense to log `cd` etc.
Before: 
```
┌  RE.PACK INIT
│
◇  Which bundler would you like to use?
│  Rspack
│
◇  Setup complete
│
◇  Next steps ──────╮
│                   │
│  cd myapp         │
│  npm install      │
│  npm start        │
│                   │
│  [ios]            │
│  npx pod-install  │
│  npm run ios      │
│                   │
│  [android]        │
│  npm run android  │
│                   │
├───────────────────╯
│
└  Done.
```
After:
```
┌  RE.PACK INIT
│
◇  Which bundler would you like to use?
│  Rspack
│
◇  Setup complete
│
◇  Next steps ──────╮
│                   │
│  npm start        │
│                   │
│  [ios]            │
│  npx pod-install  │
│  npm run ios      │
│                   │
│  [android] …
```

chore(repack-init): hide `cd` log when project exsists

---

.changeset/khaki-olives-add.md
packages/repack/src/commands/common/getEnvOptions.ts
packages/repack/src/commands/rspack/bundle.ts
packages/repack/src/commands/webpack/bundle.ts

We shouldn't exit with an error if there's no `--entry-file` option passed, because in we have the same value in `rspack.config.js` under `entry`.

fix: don't error on missing `--entry-file` when entry is defined in `rspack/webpack.config.js`

---

.changeset/dirty-boats-type.md
packages/repack/src/commands/options.ts
packages/repack/src/commands/rspack/bundle.ts
packages/repack/src/commands/rspack/start.ts
packages/repack/src/commands/webpack/bundle.ts
packages/repack/src/commands/webpack/start.ts
website/src/5.x/api/cli/start.mdx

Sync `start`'s `--webpackConfig` option with `bundle`'s to be also deprecated, also adds a warning when using and fallbacks to `--config`.

fix(cli): deprecate --webpackConfig option

---

.changeset/tough-seas-hide.md
packages/repack/android/src/main/java/com/callstack/repack/RemoteScriptLoader.kt

if an script doesn't cached the steps to run it is download, write, read, run
there is no need to read it again, 
This changes will improve performance.

fix: use already downloaded bundle

---

website/src/5.x/docs/guides/svg.md

Closes https://github.com/callstack/repack/issues/928

docs(5.x): update `svg.md`

---

.changeset/yellow-frogs-melt.md
packages/repack/src/plugins/DevelopmentPlugin.ts
packages/repack/src/plugins/NativeEntryPlugin.ts
packages/repack/src/plugins/OutputPlugin/OutputPlugin.ts
packages/repack/src/plugins/OutputPlugin/config.ts
packages/repack/src/plugins/OutputPlugin/types.ts
packages/repack/src/plugins/RepackPlugin.ts

[BREAKING] feat: remove `entryName` option from plugins

---

.changeset/pink-years-remain.md
packages/repack/package.json
packages/repack/src/loaders/reactRefreshLoader/reactRefreshLoader.ts
packages/repack/src/plugins/DevelopmentPlugin.ts
website/src/5.x/api/loaders/react-refresh-loader.md

This PR standardises the React Refresh loader implementation by using our custom loader in both Webpack and Rspack configurations, improving compatibility and reliability of Hot Module Replacement (HMR).

feat: use own ReactRefreshLoader in all environments

---

.changeset/strange-beans-glow.md
packages/repack/src/plugins/ChunksToHermesBytecodePlugin/ChunksToHermesBytecodePlugin.ts
packages/repack/src/plugins/ChunksToHermesBytecodePlugin/utils/composeSourceMaps.ts
packages/repack/src/plugins/ChunksToHermesBytecodePlugin/utils/getHermesCLIPath.ts
packages/repack/src/plugins/ChunksToHermesBytecodePlugin/utils/transformBundleToHermesBytecode.ts
packages/repack/src/plugins/CodeSigningPlugin/CodeSigningPlugin.ts
packages/repack/src/plugins/CodegenPlugin.ts
packages/repack/src/plugins/DevelopmentPlugin.ts
packages/repack/src/plugins/LoggerPlugin.ts
packages/repack/src/plugins/ManifestPlugin.ts
packages/repack/src/plugins/ModuleFederationPlugin.ts
packages/repack/src/plugins/ModuleFederationPluginV2.ts
packages/repack/src/plugins/NativeEntryPlugin.ts
packages/repack/src/plugins/__tests__/ModuleFederationPluginV2.test.ts

refactor: normalise plugin names and error formatting

---

.changeset/afraid-lies-explain.md
apps/tester-app/rspack.config.mjs
apps/tester-app/webpack.config.mjs
apps/tester-federation-v2/configs/rspack.host-app.mjs
apps/tester-federation-v2/configs/rspack.mini-app.mjs
apps/tester-federation-v2/configs/webpack.host-app.mjs
apps/tester-federation-v2/configs/webpack.mini-app.mjs
apps/tester-federation/configs/rspack.host-app.mjs
apps/tester-federation/configs/rspack.mini-app.mjs
apps/tester-federation/configs/webpack.host-app.mjs
apps/tester-federation/configs/webpack.mini-app.mjs
packages/repack/src/commands/common/config/getRepackConfig.ts
packages/repack/src/plugins/DevelopmentPlugin.ts
packages/repack/src/plugins/RepackPlugin.ts
packages/repack/src/plugins/SourceMapPlugin.ts
packages/repack/src/plugins/utils/ConfigurationError.ts
templates_v5/rspack.config.cjs
templates_v5/rspack.config.mjs
templates_v5/webpack.config.cjs
templates_v5/webpack.config.mjs

[BREAKING] feat: internal `SourceMapPlugin`

---

.changeset/large-kids-kneel.md
packages/repack/src/commands/common/config/makeCompilerConfig.ts
packages/repack/src/commands/common/config/normalizeConfig.ts

instead of normalizing the project configs, normalize the final configs obtained through merging with defaults and CLI overrides.

fix: normalize the configs at the end

---

.changeset/old-kings-build.md
apps/tester-app/rspack.config.mjs
apps/tester-app/webpack.config.mjs
apps/tester-federation-v2/configs/rspack.host-app.mjs
apps/tester-federation-v2/configs/rspack.mini-app.mjs
apps/tester-federation-v2/configs/webpack.host-app.mjs
apps/tester-federation-v2/configs/webpack.mini-app.mjs
apps/tester-federation/configs/rspack.host-app.mjs
apps/tester-federation/configs/rspack.mini-app.mjs
apps/tester-federation/configs/webpack.host-app.mjs
apps/tester-federation/configs/webpack.mini-app.mjs
packages/repack/src/commands/common/config/normalizeConfig.ts
packages/repack/src/commands/types.ts
packages/repack/src/utils/__tests__/getResolveOptions.test.ts
packages/repack/src/utils/getResolveOptions.ts
templates_v5/rspack.config.cjs
templates_v5/rspack.config.mjs
templates_v5/webpack.config.cjs
templates_v5/webpack.config.mjs

`getResolveOptions` can be now called without any params and the `platform` extensions will be resolved automatically. This makes `getResolveOptions` useful when used in static configs where `platform` variable isn't exposed.

feat: make `getResolveOptions` callable without platform

---

.changeset/many-ants-rescue.md
packages/repack/src/plugins/DevelopmentPlugin.ts

refactor: make platform optional in `DevelopmentPlugin`

---

.changeset/blue-geckos-sparkle.md
templates_v5/rspack.config.cjs
templates_v5/rspack.config.mjs
templates_v5/webpack.config.cjs
templates_v5/webpack.config.mjs

Note that it's still possible to use dynamic config with `env` as first param -> it's just that static configs are now possible 👍 
n/a

feat: slim templates

---

.changeset/eighty-phones-deny.md
apps/tester-federation-v2/configs/rspack.host-app.mjs
apps/tester-federation-v2/configs/rspack.mini-app.mjs
apps/tester-federation-v2/configs/webpack.host-app.mjs
apps/tester-federation-v2/configs/webpack.mini-app.mjs
apps/tester-federation/configs/rspack.host-app.mjs
apps/tester-federation/configs/rspack.mini-app.mjs
apps/tester-federation/configs/webpack.host-app.mjs
apps/tester-federation/configs/webpack.mini-app.mjs
packages/repack/src/loaders/assetsLoader/options.ts
packages/repack/src/utils/__tests__/__snapshots__/getAssetTransformRules.test.ts.snap
packages/repack/src/utils/__tests__/getAssetTransformRules.test.ts
packages/repack/src/utils/getAssetTransformRules.ts
packages/repack/src/utils/index.ts
templates_v5/rspack.config.cjs
templates_v5/rspack.config.mjs
templates_v5/webpack.config.cjs
templates_v5/webpack.config.mjs
website/src/5.x/api/utils/_meta.json
website/src/5.x/api/utils/get-asset-transform-rules.md

feat: getAssetTransformRules

---

website/src/5.x/docs/guides/remote-assets.md

Closes https://github.com/callstack/repack/issues/927
n/a

docs: update remote-assets

---

.changeset/breezy-bears-hammer.md
packages/repack/ios/ScriptConfig.h

Closes https://github.com/callstack/repack/issues/789
My understanding is that since all of these properties are marked as readonly, there is no need for thread synchronisation features (like atomicity) so we can safely mark them as non-atomic.

feat: make properties in `ScriptConfig` on iOS non-atomic

---

apps/tester-federation-v2/config.host-app.mjs
apps/tester-federation-v2/config.mini-app.mjs
apps/tester-federation-v2/configs/rspack.host-app.mjs
apps/tester-federation-v2/configs/rspack.mini-app.mjs
apps/tester-federation-v2/configs/webpack.host-app.mjs
apps/tester-federation-v2/configs/webpack.mini-app.mjs
apps/tester-federation/config.host-app.mjs
apps/tester-federation/config.mini-app.mjs
apps/tester-federation/configs/rspack.host-app.mjs
apps/tester-federation/configs/rspack.mini-app.mjs
apps/tester-federation/configs/webpack.host-app.mjs
apps/tester-federation/configs/webpack.mini-app.mjs

chore: fix configs in federation testers

---

website/src/latest/docs/guides/configuration.md
website/src/latest/docs/guides/configuration.mdx

Closes https://github.com/callstack/repack/issues/923
n/a

docs: configuration

---

website/src/latest/docs/migration-guides/_meta.json
website/src/latest/docs/migration-guides/expo.md

docs: remove expo migration guide

---

.changeset/shiny-starfishes-grow.md
packages/repack/src/commands/webpack/start.ts

fixed a bug where webpack command was looking for rspack config - this was not causing issue in projects where there are both rspack and webpack configs existing together.

fix: look for webpack configs in webpack start command

---

.changeset/silent-peas-think.md
packages/plugin-reanimated/src/rules.ts

reanimated plugin will now pick up on js files with `c` or `m` prefix like `cjs`, `mjs`, `cts`, `mts` etc.
n/a

fix: reanimated plugin transform js files with c and m prefix

---

website/src/latest/docs/getting-started/_meta.json
website/src/latest/docs/getting-started/quick-start.mdx
website/src/latest/docs/migration-guides/metro.md
website/src/latest/docs/migration-guides/metro.mdx

Closes https://github.com/callstack/repack/issues/929
moved manual installation and named it `migration from metro` and reworked it slightly
n/a

docs: migration from metro

---

website/src/latest/docs/migration-guides/_meta.json
website/src/latest/docs/migration-guides/repack-v4.mdx
website/src/latest/docs/migration-guides/rspack.mdx

added docs for migrating from webpack to Rspack and also linked to this migration guide from Repack v4 migration guide
n/a

docs: rspack migration guide

---

.changeset/tiny-doors-hug.md
packages/init/src/tasks/welcomeMessage.ts

replaced `REPACK INIT` with the same logo that we use in dev server
n/a

feat(init): use gradient in welcome message

---

website/src/latest/docs/getting-started/quick-start.mdx

removed deployment from quick start to keep it simpler while still mentioning the Deployment page in the the bottom tip block
n/a

docs: remove repeated deployment from quick start

---

.changeset/cool-bats-peel.md
packages/repack/src/commands/common/config/normalizeConfig.ts

we only do a shallow copy of config object in `makeCompilerConfig` and editing nested props like `config.output.path` would result in overwriting the `path` field on the same object (because of a shallow copy) - we can't make deep copy because configs might contain non-serializable fields like functions so in this PR, I've fixed the normalisation logic by collecting properties to normalise first and making a config object out of them and then using `webpack-merge` to merge the config with the one with normalised values.

fix: normalize carefully with `webpack-merge`

---

.changeset/old-cooks-joke.md
packages/repack/src/commands/common/config/__tests__/normalizeConfig.test.ts
packages/repack/src/commands/common/config/normalizeConfig.ts

fix: normalizeConfig resolve.extension merging

---

.changeset/good-apes-grab.md
packages/repack/src/plugins/DevelopmentPlugin.ts

After removing and testing in debug everything works the same way as before in TesterApp.
1. Open TesterApp, everything should work in the same way as before 👍

fix: remove enforcement of output filenames in dev

---

.changeset/weak-candles-dream.md
packages/dev-server/package.json
packages/dev-server/src/plugins/devtools/devtoolsPlugin.ts
pnpm-lock.yaml

Closes #1080 
We still need to fix `/open-stack-frame` behaviour since it seems to be broken for some time (we need to rewrite `webpack://` urls into actual filepaths
dedicated bug report: https://github.com/callstack/repack/issues/1082

refactor: drop `@react-native-community/cli-server-api` dep

---

.changeset/breezy-garlics-shop.md
packages/repack/src/plugins/DevelopmentPlugin.ts

prevent an issue in development like below:
this was caused because even though there was no container bundle being emitted, we were adjusting it entries, which caused it to be actually emitted which should not happen in the first place

fix: prevent emitting unused container bundles in development

---

.changeset/light-students-lay.md
packages/dev-server/src/createServer.ts

Since we are not hiding runtime client logs in the dev server output so this message was irrelevant and confusing to the users.

fix: hide javascript logs have moved message

---

.changeset/light-pumpkins-compete.md
packages/init/src/tasks/modifyDependencies.ts
packages/init/versions.json

refactor: use highest minor version for repack

---

.changeset/weak-hairs-serve.md
packages/repack/src/commands/common/config/__tests__/normalizeConfig.test.ts
packages/repack/src/commands/common/config/getCommandConfig.ts
packages/repack/src/commands/common/config/normalizeConfig.ts

Fixed an issue where overriding the devServer port would not be reflected in `output.publicPath`.

fix: `publicPath` in dev doesnt use overriden port

---

.changeset/long-cooks-attend.md
packages/repack/src/commands/common/config/loadProjectConfig.ts

Since `require(esm)` is a thing, our current method of loading projects with require first and then dynamic import fails - this PR changes this to support newer node versions by trying dynamic import first

fix: try loading config through esm import first

---

.changeset/four-walls-beg.md
packages/repack/src/commands/common/config/getConfigFilePath.ts

fix: don't convert `.mjs` config path to url twice on Windows

---

.changeset/pretty-dragons-destroy.md
packages/repack/src/modules/FederationRuntimePlugins/ResolverPlugin.ts
packages/repack/src/modules/FederationRuntimePlugins/__tests__/ResolverPlugin.test.ts

This PR fixes the incorrect URL rebasing when resolving MF2 remotes. Previously we were only replacing the base URL (without path) and this caused a regression when `publicPath` of a remote is set to a URL with a path (e.g. `http://localhost:8081/ios`). 
Since all MF2 assets are always generated with a flat directory structure (meaning they will all exist next to each other, in the same directory), we can take the last part of the URL (after last '/') and rebase it onto the publicPath of an entrypoint of a remote.
Examples:
| URL Type | Example 1 | Example 2 |
|----------|-----------|-----------|
| Initial URL | `noop:///asset.js` | `http://localhost:8081/ios/chunk.js` |
| Entry URL | `https://example.com/ios/mf-manfiest.js` | `https://example.com/ios/entry.js` |
| Target URL | …

fix: include path in MF2 remote public path

---

.changeset/eighty-yaks-kick.md
.changeset/smooth-impalas-protect.md
.changeset/spicy-poems-itch.md
apps/tester-app/rspack.config.mjs
apps/tester-app/webpack.config.mjs
apps/tester-federation-v2/configs/rspack.host-app.mjs
apps/tester-federation-v2/configs/rspack.mini-app.mjs
apps/tester-federation-v2/configs/webpack.host-app.mjs
apps/tester-federation-v2/configs/webpack.mini-app.mjs
apps/tester-federation/configs/rspack.host-app.mjs
apps/tester-federation/configs/rspack.mini-app.mjs
apps/tester-federation/configs/webpack.host-app.mjs
apps/tester-federation/configs/webpack.mini-app.mjs
packages/repack/src/utils/__tests__/getResolveOptions.test.ts
packages/repack/src/utils/getResolveOptions.ts
pnpm-lock.yaml
tests/metro-compat/jest.setup.js
tests/metro-compat/package.json
tests/metro-compat/resolver/__tests__/index-test.js
tests/metro-compat/resolver/__tests__/package-exports-test.js
tests/metro-compat/resolver/__tests__/package-imports-test.js
tests/metro-compat/resolver/__tests__/symlinks-test.js
tests/metro-compat/resolver/__tests__/utils.js
tests/metro-compat/resolver/resolve.ts

Since Metro enables package exports by default now, it's about time we finish the support for package exports in Re.Pack as well. For now we will keep it disabled by default but we might enable it in the next minor/major version depending on feedback from users.
Alignment with updated tests from Metro allowed to find missing pieces in the package exports configuration which in turn enabled package exports to work in all of the testers 🎉

feat: update `getResolveOptions`

---

.changeset/calm-pandas-nail.md
packages/repack/src/loaders/assetsLoader/__tests__/__snapshots__/assetsLoader.test.ts.snap
packages/repack/src/loaders/assetsLoader/__tests__/assetsLoader.test.ts
packages/repack/src/loaders/assetsLoader/convertToRemoteAssets.ts
packages/repack/src/loaders/assetsLoader/inlineAssets.ts
packages/repack/src/modules/DevServerClient.ts
packages/repack/src/modules/WebpackHMRClient.ts

fix: handle RN 0.79 deep import changes

---

.changeset/tasty-snails-lie.md
packages/repack/src/modules/ScriptManager/ScriptManager.ts

Pass `referenceUrl` to `prefetchScript` so that it's signature is equal to that of `loadScript` and behaves similarly when resolving scripts
n/a

refactor: allow passing referenceUrl to prefetchScript

---

.changeset/chilled-bats-draw.md
packages/init/versions.json

Bumped versions of dependencies that are installed with a new project when using `repack-init`
n/a

chore: bump versions in init

---

.changeset/shaggy-seals-return.md
packages/repack/babel.config.js
packages/repack/src/modules/FederationRuntimePlugins/ResolverPlugin.ts
packages/repack/src/modules/FederationRuntimePlugins/__tests__/ResolverPlugin.test.ts

feat: use `registerRemote` hook in ResolverPlugin

---

.changeset/blue-numbers-protect.md
packages/repack/jest.config.js
packages/repack/src/commands/common/config/__tests__/loadProjectConfig.test.ts
packages/repack/src/commands/common/config/loadProjectConfig.ts

Prevent swallowing errors originating in project config files by determining whether to use import or require based on config extension and project type (`commonjs` or `module`) as a fallback

fix: check for ESM config instead of try catch

---

.changeset/perfect-news-jog.md
.changeset/spicy-spiders-help.md
packages/repack/src/commands/common/config/getCommandConfig.ts
packages/repack/src/commands/common/config/makeCompilerConfig.ts
packages/repack/src/commands/common/index.ts
packages/repack/src/commands/common/resetPersistentCache.ts
packages/repack/src/commands/options.ts
packages/repack/src/commands/rspack/bundle.ts
packages/repack/src/commands/rspack/start.ts
packages/repack/src/commands/types.ts
packages/repack/src/commands/webpack/bundle.ts
packages/repack/src/commands/webpack/start.ts
website/src/latest/api/cli/bundle.mdx
website/src/latest/api/cli/start.mdx

This PR add persistent caching by default for `start` command, and adds support for resetting the transformation cache via a old-new `--reset-cache` flag. 
**Users can opt out of persistent cache by setting `cache: false` in the project configuration.**
- Enabled persistent cache by default in `start` command
- Implemented `--reset-cache` flag functionality for both `start` and `bundle` commands
- Added cache reset utility that handles both Rspack and Webpack cache directories
- Supports both default and custom cache locations
- Provides clear warnings when cache reset fails or when cache is outside project directory
- Updated documentation to reflect new functionality
- Removed "unsupported" notes from `--reset-cache` flag descriptions
- Added new documentation sections explaining the …

feat: enable persistent cache by default in start command

---

.changeset/good-mirrors-bow.md
packages/repack/src/commands/common/config/validatePlugins.ts

fix: use readFileSync instead of require in `validatePlugins`

---

packages/plugin-expo-modules/package.json
packages/plugin-nativewind/package.json
packages/plugin-reanimated/package.json

since we're releasing plugins all at once, it makes sense to have the peerDependency set to the same version
n/a

chore: pin plugin versions to current version of Re.Pack

---

.changeset/shy-worlds-type.md
packages/repack/package.json
packages/repack/src/commands/common/__tests__/setupInteractions.test.ts
packages/repack/src/commands/common/setupInteractions.ts
packages/repack/src/commands/rspack/profile.ts
packages/repack/src/commands/rspack/start.ts
pnpm-lock.yaml

added support for `RSPACK_PROFILE` env var, similar how it is in `@rspack/cli`.
To learn how to use it, visit [Rspack documentation](https://rspack.dev/contribute/development/tracing#tracing)

feat: add support for tracing rspack

---

.changeset/cold-kids-yawn.md
packages/repack/src/modules/FederationRuntimePlugins/ResolverPlugin.ts
packages/repack/src/modules/FederationRuntimePlugins/__tests__/CorePlugin.test.ts
packages/repack/src/modules/FederationRuntimePlugins/__tests__/ResolverPlugin.test.ts
packages/repack/src/modules/ScriptManager/ScriptManager.ts
packages/repack/src/modules/ScriptManager/__tests__/ScriptManager.test.ts
packages/repack/src/modules/ScriptManager/__tests__/ScriptManagerHooks.test.ts
packages/repack/src/plugins/RepackTargetPlugin/implementation/init.ts
packages/repack/src/types/runtime-globals.d.ts

`registerRemote` is a sync hook and previous approach with adding resolvers asynchronously proves very brittle as seen in https://github.com/ZephyrCloudIO/zephyr-repack-example
The hook is triggered very early in the runtime, before initialisation of RN Core & ScriptManager. Since there is no reliable way to wait for ScriptManager to be initialised, in ResolverPlugin we now check whether the `ScriptManager` instance is present in runtime: 
- if ScriptManager is initialized, we add resolver normally just as before
- if ScriptManager is not initialised, we add a resolver to queue that will be consumed at the end of ScriptManager initialisation sequence (ctor).
The queue is an internal runtime mechanism and is not exposed to the user. 
Ideally, in the future, we could be replace it by …

fix: enqueue resolvers before `ScriptManager` init

---

.changeset/plugin-nativewind.md
packages/plugin-nativewind/src/plugin.ts

nativewind/preset chooses web, when process.env.NATIVEWIND_OS !== "native" or is undefined.
The Re-Pack plug-in never sets that variable, so Tailwind’s web defaults win and the angle variables
(--tw-rotate, --tw-skew-x/y) are emitted as bare 0 → Android crashes.
Metro does set the var (via withNativeWind()), so the two bundlers behave differently.
Force the platform passed to nativewind/preset.
*  "native" (default) | "web" | undefined (use env as-is)
* When Tailwind runs, the **native** preset adds
`--tw-rotate: 0deg; --tw-skew-x:0deg; --tw-skew-y:0deg` to the reset layer,
so the generated CSS already has the correct units.
* The loader no longer needs to post-process `cssToReactNativeRuntime` output,
and palette colours work unchanged.

fix: expose missing `NATIVEWIND_OS` in NativeWind plugin

---

website/src/latest/docs/features/_meta.json
website/src/latest/docs/features/module-federation.md
website/src/latest/docs/features/module-resolution.md
website/src/latest/docs/getting-started/_meta.json
website/src/latest/docs/getting-started/bundlers.md

docs: fix V4 links

---

packages/plugin-nativewind/README.md
website/src/latest/docs/features/_meta.json
website/src/latest/docs/features/nativewind.mdx

Adds a dedicated page to documentation for NativeWind. 
Also updates dead links in plugin's readme.

docs: add documentation for NativeWind plugin

---

.changeset/fruity-shrimps-shave.md
packages/init/src/tasks/createNewProject.ts
packages/init/versions.json

To prevent incompatibilities with cutting-edge versions of `react-native` and creating broken projects, `@callstack/repack-init` is now locked onto explicitly stated latest supported version of `react-native`.

fix: lock version of `react-native` installed by `init`

---

.changeset/salty-rockets-kiss.md
packages/repack/android/src/main/java/com/callstack/repack/FileSystemScriptLoader.kt

fix: android build after changes to FileSystemScriptLoader

---

.changeset/khaki-teams-enjoy.md
packages/repack/android/CMakeLists.txt
packages/repack/android/build.gradle

Closes #1191
Analyze apk result:

feat: support 16kb page sizes on Android

---

.changeset/public-mugs-smile.md
packages/repack/android/build.gradle

We did additional tests and it seems related to the old version of the jwt library.
This upgrade also fixes a vulnerability with all the versions of the library < 9.37.2 (see [here](https://mvnrepository.com/artifact/com.nimbusds/nimbus-jose-jwt?))
Closes #1198
n/a

fix: upgrade nimbus jose android dependency

---

.github/workflows/test.yml

chore: pin github actions to specific commit

---

.github/workflows/test.yml
CONTRIBUTING.md
package.json
pnpm-lock.yaml
pnpm-workspace.yaml
tests/metro-compat/package.json
website/package.json

This PR bumps Node 18 to Node 20 in the repo but does not influence the actual published packages since that would be a breaking change.

chore: use node 20+ for development

---

.changeset/late-dragons-fail.md
packages/repack/src/utils/getFlowTransformRules.ts

Add `react-native-modal-datetime-picker` to list of libs with flow types
n/a

fix: add `react-native-modal-datetime-picker` to flow libs

---

.changeset/bumpy-bags-beam.md
packages/repack/src/utils/getSwcLoaderOptions.ts

fix: add missing SWC rules

---

.changeset/clear-rooms-hammer.md
packages/repack/package.json
pnpm-lock.yaml

feat: support RN 80 flow transforms

---

.changeset/gentle-pandas-pull.md
packages/dev-server/package.json
packages/dev-server/src/createServer.ts
pnpm-lock.yaml

Upgrade React Native DevTools integration to support RN 0.80 and fix logger compatibility - the logs are now formatted with `util.format` from Node

feat: support React Native 0.80 in DevTools

---

.changeset/twenty-pets-wear.md
packages/dev-server/src/createServer.ts
packages/dev-server/src/types.ts
packages/dev-server/src/utils/normalizeOptions.ts

This PR introduces a new `devServer.setupMiddlewares` configuration option that allows developers to customize the middleware stack in the DevServer.
```javascript
// rspack.config.mjs
export default {
// ...
devServer: {
setupMiddlewares: (middlewares, devServer) => {
// Your middleware setup code here
return middlewares;
},
},
};
```
Add routes directly to the Fastify instance:
```javascript
// rspack.config.mjs
export default {
devServer: {
setupMiddlewares: (middlewares, devServer) => {
devServer.get('/setup-middleware/some/path', (_, response) => {
response.send('setup-middlewares option GET');
});
return middlewares;
},
},
};
```
Use `unshift()` to run middleware before all other middlewares:
```javascript
// rspack.config.mjs
export default {
devServer: {
setupMiddlewares: …
```

feat: support custom middleware through `setupMiddlewares`

---

packages/repack/src/utils/defineConfig.ts

This pull request updates the return type of the async config function for RsPack. Currently, it is declared as RspackConfiguration, but it should be RepackRspackConfig to align with the other elements in the config type union.
Use an async function to configure the test app. Note that it currently doesn't accept the correct configuration. Check out this branch to see the difference.

fix: async config return type

---

.changeset/little-turkeys-go.md
packages/repack/src/commands/rspack/start.ts
packages/repack/src/commands/webpack/start.ts

fix: `REPACK_VERBOSE` env not affecting dev server logs

---

.changeset/little-cats-raise.md
packages/repack/src/logging/reporters.ts

This PR deals with the problem of repeated logs when bundling with Rspack, preventing terminal log scheduler interruptions caused by multiple instances of `Terminal` spawned inside the same process.

fix: use singleton terminal instance per process

---

.changeset/twelve-rats-draw.md
apps/tester-app/rspack.config.mjs
apps/tester-federation-v2/configs/rspack.host-app.mts
apps/tester-federation-v2/configs/rspack.mini-app.mts
apps/tester-federation/configs/rspack.host-app.mts
apps/tester-federation/configs/rspack.mini-app.mts
packages/repack/src/commands/common/config/getRepackConfig.ts
website/src/latest/docs/guides/configuration.mdx

This PR enables `experiments.parallelLoader` by default for Rspack configurations.

feat: enable parallel loader by default

---

.changeset/rare-gifts-sip.md
packages/repack/src/loaders/babelLoader/babelLoader.ts
packages/repack/src/loaders/babelSwcLoader/babelSwcLoader.ts
packages/repack/src/loaders/babelSwcLoader/utils.ts

Always use `@callstack/repack` as caller.name passed to Babel / SWC

fix: use consitent name as caller regardless of loader

---

.changeset/funny-clubs-see.md
packages/repack/src/loaders/babelSwcLoader/swc.ts

Exclude `transform-typescript` from babel rules when detected through `babel-swc-loader`

fix: exclude transform-typescript when present

---

.changeset/lemon-paths-allow.md
packages/repack/android/src/main/java/com/callstack/repack/FileSystemScriptLoader.kt

https://github.com/callstack/repack/pull/1243 intoduced a bug on Android that caused compilation errors - to address it, I've added a noop handler for prefetch calls on Android - the function will resolve correctly instead of throwing an error because of unsupported protocol, which was the primary intent behind the PR mentioned

fix: use noop handler for filesystem prefetch calls on Android

---

.changeset/mean-dodos-hear.md
.changeset/tangy-lines-cheer.md
apps/tester-app/rspack.config.mjs
packages/plugin-reanimated/src/loader.ts
packages/plugin-reanimated/src/plugin.ts
packages/plugin-reanimated/src/rules.ts

This PR adds a way to pass custom options to Reanimated/Worklets plugin.
It also adds a check to ensure `react-native-worklets` is installed when using Reanimated >= 4
Example:
```js
new ReanimatedPlugin({
babelPluginOptions: { 
relativeSourceLocation: true 
},
}),
```

feat: support passing options to reanimated / worklets plugin

---

packages/repack/src/commands/common/config/getMinimizerConfig.ts

fix: terser condition

---

.changeset/smart-dryers-doubt.md
apps/tester-app/ios/Podfile.lock
apps/tester-federation-v2/ios/Podfile.lock
apps/tester-federation/ios/Podfile.lock
packages/repack/src/plugins/ModuleFederationPluginV1.ts
packages/repack/src/plugins/ModuleFederationPluginV2.ts
packages/repack/src/plugins/__tests__/ModuleFederationPluginV1.test.ts
packages/repack/src/plugins/__tests__/ModuleFederationPluginV2.test.ts

Closes #1282 
When `import: false` is set for shared `react-native`, the same is now applied to its deep imports (`react-native/`, `@react-native/`).
```ts
shared: {
react: { singleton: true, eager: false },
'react-native': { singleton: true, eager: false, import: false },
// deep imports set automatically by the Re.Pack MF plugin
'react-native/': { singleton: true, eager: false },
'@react-native/': { singleton: true, eager: false },
}
```
```ts
shared: {
react: { singleton: true, eager: false, import: false },
'react-native': { singleton: true, eager: false, import: false },
// deep imports set automatically by the Re.Pack MF plugin
'react-native/': { singleton: true, eager: false, import: false },
'@react-native/': { singleton: true, eager: false, import: false },
}
```

fix: pin emitting RN deep imports shared to RN shared
