callstack/repack

.eslintrc.js, examples/TesterApp/webpack.config.js, package-lock.json, package.json, src/webpack/utils/__tests__/parseCliOptions.test.ts, src/webpack/utils/parseCliOptions.ts, templates/webpack.config.js
- Adds minification configuration to Webpack config template.
- Infer `minimize` from `dev` when building with `webpack-bundle` command.
1. Build application in release mode.
2. The bundle should be minified and runnable.
=> feat: add minification support

examples/TesterApp/webpack.config.js, templates/webpack.config.js
Update `webpack.config.js` template to a new format.
1. Run the app.
2. Start development server or bundle the app.
=> feat: update Webpack config template

README.md
As it took me some time to launch repack for the first time I think these additional lines gonna be timesaver
=> docs: more detailed readme for usage

packages/TesterApp/android/app/build.gradle, packages/TesterApp/android/app/src/main/java/com/testerapp/MainApplication.java, packages/TesterApp/android/settings.gradle, packages/TesterApp/package.json, packages/repack/android/build.gradle, packages/repack/android/gradle.properties, packages/repack/android/src/main/java/com/callstack/nativepack/RemoteChunkLoader.kt
- Fixes #40 
- Fixes Kotlin build error from #62 
1. Run the application and make `fetch`/`XMLHttpRequest` for a resource which responds with cookies.
2. The app should not crash.
Tested on RN 0.64.
=> fix: add okhttp-urlconnection to prevent crashes when using cookies, minor Android native module tweaks

README.md
Badges links were pointing to unexisting part of the readme, changed it to point to proper sections on the documentation website
Click on affected badges before and after
=> docs: update links in badges

README.md
Could be I'm missing something I believe this may be a typo in the README
Harmes Engine => Hermes Engine
N/A
=> Correct possible typo

packages/repack/src/server/DevServerProxy.ts
Fixes the following error introduced in #65 :
```
[DevServerProxy] Promise may not be fulfilled with 'undefined' when statusCode is not 204 {
err: {
type: 'FastifyError',
message: "Promise may not be fulfilled with 'undefined' when statusCode is not 204",
stack: "FastifyError: Promise may not be fulfilled with 'undefined' when statusCode is not 204\n" +
'    at /<redacted>/node_modules/fastify/lib/wrapThenable.js:30:30\n' +
'    at processTicksAndRejections (internal/process/task_queues.js:95:5)',
name: 'FastifyError',
code: 'FST_ERR_PROMISE_NOT_FULFILLED',
statusCode: 500
}
}
```
=> fix: fastify reply error in DevServerProxy

packages/repack/src/client/chunks-api/ChunkManager.ts
- Adds better error handling for resolution errors
- Adds `forceRemoteChunkResolution` options
=> feat: better error handling & forceRemoteChunkResolution option

packages/dashboard/src/components/Button.tsx, packages/dashboard/src/pages/Dash/CompilationTrigger.tsx, packages/dashboard/src/pages/Dash/Dash.tsx
Allow to trigger compilation for given platform from the dashboard without using an application or curl/HTTP client.
=> feat: allow to trigger compilation from dashboard

packages/repack/src/Reporter.ts, packages/repack/src/server/DevServerProxy.ts, packages/repack/src/server/MultipartResponse.ts
support multipart/mixed bundle on the react-native client
progress can be seen on the top of the client & bundle is downloaded and works as expected.
=> feat: client bundling progress support

packages/repack/src/Reporter.ts, packages/repack/src/server/DevServerProxy.ts, packages/repack/src/server/MultipartResponse.ts
Based on #167 but with `prettier/prettier` rule disabled for `MultipartResponse.ts`, due to ESLint going haywire there.
=> feat: bundle progress

templates/webpack.config.cjs, templates/webpack.config.mjs, website/package.json, website/static/diffs/repack_v2-v3.diff
SVG should not be differently handled by default templates.
=> fix: remove svg from default template

.changeset/blue-students-talk.md, packages/TesterApp/index.js, packages/TesterApp/src/MiniAppsContainer.js, packages/TesterApp/src/RemoteContainer.js, packages/repack/src/modules/ScriptManager/Script.ts, packages/repack/src/modules/ScriptManager/ScriptManager.ts, packages/repack/src/modules/ScriptManager/__tests__/ScriptManager.test.ts, packages/repack/src/modules/ScriptManager/federated.ts, packages/repack/src/modules/ScriptManager/types.ts, website/docs/code-splitting/caching-versioning.md, website/docs/code-splitting/code-push.md, website/docs/code-splitting/guide-async-chunks.md, website/docs/code-splitting/local-vs-remote-chunks.md, website/docs/code-splitting/usage.md
Add support for multiple resolvers.
Related to #199 
- Tests should pass.
- TesterApp should load and display chunks w/o errors.
=> feat(repack): support multiple resolvers

README.md, website/docs/about.md, website/docs/getting-started.md, website/docusaurus.config.js
Add links to examples repo
No changeset is necessary.
=> docs: add links to examples

.changeset/unlucky-dots-share.md, packages/repack/src/modules/ScriptManager/federated.ts, packages/repack/src/webpack/federated.ts
Modify logic of `importModule` and `createRemote` functions to properly handle bi-directionals imports in Module Federation.
N/A
=> fix: add checks for bi-directional containers and cycling dependencies

packages/TesterApp/ios/Podfile.lock
Update Re.Pack version in TesterApp
=> chore: update Podfile.lock in TesterApp

.changeset/brown-gorillas-breathe.md, packages/dev-server/package.json, packages/dev-server/src/createServer.ts, yarn.lock
Introduce `fastify-favicon` plugin to avoid GET 400 /favicon.icon error code when accessing bundle via browser
=> feat: introduce fastify favicon

.changeset/hungry-apes-begin.md, packages/TesterApp/ios/Podfile.lock
Update pods in TesterApp to match `next7` version
=> chore: update pods

.changeset/chilled-deers-dream.md, packages/dev-server/package.json
Expose `archive` script in `dev-server` for testing purpose.
=> chore: archive script in devserver

website/docs/migration-guides/repack-v2-to-v3.mdx, website/static/diffs/repack_v2-v3.diff
Migration guide from V2 to V3 of Re.Pack
=> docs: migration guide v2-v3

website/docs/code-splitting/caching-versioning.md
Fix variable name to align with received parameter name `chunkId` -> `scriptId`. Bug fixed in PR is related only to docs and does not affect any other code.
=> docs: replace 'chunkId' with 'scriptId'

packages/repack/src/webpack/Compiler.ts
=> fix(webpack/Compiler): assetsCache miss on windows

.gitignore
I'm using WebStorm as my main IDE and it's frustrating to keep changes inside `.idea` directory from polluting PRs. I'm adding it to .gitignore file to prevent that in the future.
There's no need to test that.
=> chore: Ignore inteliJ .idea directory

website/docs/getting-started.mdx, website/versioned_docs/version-2x/getting-started.mdx
This PR adds info about new shape of Xcode config for RN versions newer than 0.69.0. Change is added in both v3 and v2 docs.
=> docs: Add info about new shape of xcode config for RN 0.69+

README.md
Could be helpful for those wanting to set up module federation in a more comprehensive setup
Docs
=> Add link to super app showcase

.changeset/fast-apricots-kick.md, package.json, packages/init/.eslintrc.cjs, packages/init/.prettierrc.cjs, packages/init/README.md, packages/init/package.json, packages/init/src/bin.ts, packages/init/src/index.ts, packages/init/src/tasks/addDependencies.ts, packages/init/src/tasks/checkPackageManager.ts, packages/init/src/tasks/checkReactNative.ts, packages/init/src/tasks/createWebpackConfig.ts, packages/init/src/tasks/handleReactNativeConfig.ts, packages/init/src/tasks/modifyAndroid.ts, packages/init/src/tasks/modifyIOS.ts, packages/init/src/types/xcode.d.ts, packages/init/src/utils/logger.ts, packages/init/tsconfig.json, website/docs/getting-started.mdx, yarn.lock
This PR introduces `repack-init`, a utility npm package that automates the process of integrating the `Repack` bundler into React Native projects.
Here's a summary of the functionality `repack-init` provides:
- **Package Manager Detection:** Identifies the package manager (npm or yarn) being used in the project.
- **React Native Verification:** Checks whether React Native is installed in the project, and what version is being used.
- **Dependency Addition:** Utilizes the established package manager to add necessary dependencies to the React-Native project.
- **Configuration of React Native Config:** Checks for the existence of `react-native.config.js` and adds or modifies the necessary fields (commands).
- **Webpack Configuration:** Creates and configures `webpack.config.js` based on …
=> feat: repack-init

.changeset/olive-jeans-film.md, packages/init/README.md, packages/init/package.json
Fix config in `bin` field in `package.json` so it can be used properly with `npx`
=> Fix: repack-init executable config

README.md
Remove go-to badges as they clutter the rest. Fix the build badge. Add missing Discord chat and sponsor badges.
=> docs: cleanup badges; fix build; add discord

.github/workflows/deploy-pr.yml
Fix the if condition in `deploy-pr` workflow to properly enable manual dispatch
=> chore: fix manula doc preview

packages/repack/src/webpack/federated.ts, packages/repack/src/webpack/plugins/RepackPlugin.ts
Hi, I fixed the wrong imports on the example sections.
=> Example typo fix

packages/TesterApp/webpack.config.mjs, packages/repack/src/commands/utils/getWebpackConfigPath.ts
see #215
- check if all runs good on Linux, I tested only on Windows, but I've added Os check to prevent different behaviors from before
- check if failing tests are related to two edits in start.ts and bundle.ts (sorry for this, I'm not so much into tests)
=> fix: ERR_UNSUPPORTED_ESM_URL_SCHEME on Windows (#215)

.changeset/chatty-windows-type.md, packages/TesterApp/android/app/src/main/res/values/styles.xml, packages/TesterApp/ios/TesterApp/Info.plist, packages/TesterApp/src/App.tsx
Ensure we're always running light theme in TesterApp.
=> chore(TesterApp): force light theme

packages/init/tsconfig.json
fix ts setup in init to account for `pnpm` node_modules structure
=> fix: ts setup in init

.gitignore, package.json, pnpm-lock.yaml, turbo.json
upgrade + reduced output to errors-only, will see how it works in the long run
=> chore: upgrade turborepo

.changeset/bright-pillows-argue.md, packages/repack/src/commands/bundle.ts
To clarify what are errors exactly, we need to log them before exist.
=> fix: log errors before exit

.changeset/config.json, package.json, pnpm-lock.yaml
=> chore: update changesets and adjust config

.github/actions/deploy-website/action.yml, .github/workflows/deploy-old-preview.yml, .github/workflows/deploy-old-prod.yml
old website deploys are now disabled, still possible to deploy them manually for now
n/a
=> chore: disable old website deploys

new-website/src/2.x/docs/known-issues.md, new-website/src/3.x/docs/known-issues.md, website/docs/known-issues.md, website/versioned_docs/version-2x/known-issues.md
This PR fixes typo in docs
Not needed
=> fix: docs typo

README.md, new-website/src/2.x/docs/code-splitting/_meta.json, new-website/src/2.x/index.md, new-website/src/3.x/docs/_meta.json, new-website/src/3.x/docs/code-splitting/_meta.json, new-website/src/3.x/docs/getting-started.mdx, new-website/src/3.x/index.md
fixed typos & aligned sidebars in the docs
n/a
=> chore: docs cleanup

pnpm-lock.yaml, website/package.json, website/src/styles/index.css
upgrade `rspress` to 1.19.1 & remove some overrides from styles
n/a
=> chore: adjust doc sidebar

.github/workflows/test.yml
Added Node22 to tests env matrix on CI
n/a
=> chore: run CI tests on node 22

website/src/4.x/docs/_meta.json, website/src/4.x/docs/plugins/_meta.json, website/src/4.x/docs/plugins/code-signing.md, website/src/4.x/docs/plugins/index.md
added docs for code-signing, along with guide for setting it up
Closes #519
Closes #594
n/a
=> docs: code-signing

website/src/4.x/docs/plugins/_meta.json, website/src/4.x/docs/plugins/hermes.md
slightly reworked version of hermes plugin docs for v4
n/a
=> docs: hermes plugin

website/src/4.x/docs/_meta.json, website/src/4.x/docs/guides/_meta.json, website/src/4.x/docs/guides/inline-assets.md, website/src/4.x/docs/guides/remote-assets.md, website/src/4.x/docs/guides/svg.md, website/src/4.x/docs/loaders/assets-loader.md
Added slightly revised docs for assets to v4 documentation, the guides were fully left intact.
n/a
=> docs: assets

.github/workflows/test.yml
Disable running CI when working on docs
n/a
=> chore: don't run CI job when working on website

website/src/4.x/docs/about.md
Updated about page in the docs
n/a
=> docs: update about page

website/src/4.x/docs/getting-started.mdx
updated getting-started for v4
n/a
=> docs: update getting-started

pnpm-lock.yaml, website/package.json
=> chore: update rspress to 1.20.1

.changeset/big-spiders-guess.md, .changeset/bright-pillows-argue.md, .changeset/dry-trains-join.md, .changeset/early-radios-grow.md, .changeset/fair-experts-wave.md, .changeset/fast-geckos-wonder.md, .changeset/fluffy-insects-prove.md, .changeset/friendly-insects-dream.md, .changeset/funny-seals-judge.md, .changeset/good-planes-confess.md, .changeset/great-baboons-tease.md, .changeset/grumpy-tigers-eat.md, .changeset/hmr-client-prove.md, .changeset/honest-wolves-act.md, .changeset/kind-beds-clap.md, .changeset/kind-scissors-kick.md, .changeset/modern-dryers-itch.md, .changeset/plenty-kangaroos-whisper.md, .changeset/polite-islands-fetch.md, .changeset/sharp-stingrays-wave.md, .changeset/tidy-dogs-grab.md, .changeset/warm-numbers-doubt.md, .changeset/yellow-spiders-smash.md
reworked descriptions of changesets so that the release notes can be generated easier. I've removed the longer descriptions for migrating since they are available as part of Migration Guide
=> chore: prepare changesets for release

website/rspress.config.ts
=> fix: broken og image link

website/rspress.config.ts
=> chore: set 4.x as active docs

package.json
Fixed wrong filtering in website commands
[x] Tested locally
=> chore: fixed filtering in website commands

pnpm-lock.yaml, website/package.json
=> chore: bumped `rspress` version

packages/TesterApp/ios/Podfile.lock, packages/TesterApp/package.json, packages/repack/package.json, pnpm-lock.yaml
=> chore: upgrade RN to 0.74.3

.github/workflows/test.yml, .npmrc, package.json, packages/TesterApp/package.json, packages/dev-server/package.json, packages/dev-server/tsconfig.json, packages/init/package.json, packages/repack/package.json, pnpm-lock.yaml, turbo.json, website/package.json
upgraded pnpm, turborepo, typescript + setup watching dev task
n/a
=> chore: upgrade tooling

.changeset/fast-cats-think.md, packages/repack/src/webpack/plugins/OutputPlugin.ts
Closes #672
Thank you @linhh-phv for suggesting the fix!
=> fix: infinite loop when traversing the chunk graph in `OutputPlugin`

.github/ISSUE_TEMPLATE/1-bug-report.yml
- make repro required
- make repro steps required
- more verbose descriptions for repro URL & repro steps
n/a
=> chore: update issue templates

.prettierignore, .prettierrc.cjs, .prettierrc.js, CODE_OF_CONDUCT.md, apps/tester-app/.prettierrc.js, apps/tester-app/package.json, apps/tester-app/tsconfig.json, apps/tester-federation/.prettierrc.js, apps/tester-federation/package.json, apps/tester-federation/src/host/App.tsx, apps/tester-federation/src/host/navigation/MainNavigator.tsx, apps/tester-federation/src/host/screens/DetailScreen.tsx, apps/tester-federation/src/host/screens/HomeScreen.tsx, apps/tester-federation/src/mini/navigation/MainNavigator.tsx, apps/tester-federation/tsconfig.json, package.json, packages/dev-server/.prettierrc.cjs, packages/dev-server/tsconfig.json, packages/init/.prettierrc.cjs, packages/repack/.clang-format, packages/repack/.prettierrc.js, packages/repack/src/commands/start.ts, packages/repack/src/webpack/plugins/ModuleFederationPlugin.ts, packages/repack/tsconfig.json, pnpm-lock.yaml, pnpm-workspace.yaml, tests/metro-compat/.prettierrc.js
unified & simplified prettier setup for the whole repo
n/a
=> chore: unified prettier setup & reformat

.changeset/itchy-dodos-protect.md, packages/repack/commands.js
=> fix: missing reset cache flag

.changeset/brave-readers-sleep.md, packages/repack/src/plugins/ModuleFederationPluginV2.ts
=> feat: expose _options ModuleFederationPluginV2.ts

.changeset/brave-readers-sleep.md, packages/repack/src/plugins/ModuleFederationPluginV2.ts
=> Revert "feat: expose _options ModuleFederationPluginV2.ts"

website/src/5.x/api/loaders/flow-loader.md
=> docs: flow-loader

website/src/5.x/api/loaders/assets-loader.md
=> docs: assets loader

packages/repack/src/loaders/reactRefreshCompatLoader/index.ts, packages/repack/src/loaders/reactRefreshLoader/index.ts, packages/repack/src/loaders/reactRefreshLoader/reactRefreshLoader.ts, packages/repack/src/plugins/DevelopmentPlugin.ts, website/src/5.x/api/loaders/react-refresh-loader.md
=> refactor: reactRefreshLoader

.changeset/quick-rats-knock.md, packages/repack/src/rules/flowTypedModulesLoadingRules.ts
fix https://github.com/callstack/repack/issues/851
=> fix: add react-native-inappbrowser-reborn in flowTypedModulesLoadingRules.ts

website/theme/index.tsx
=> docs: fix banner, adjust message

website/src/4.x/docs/code-splitting/react-navigation.md
With React Navigation 7.x there's [`screenLayout`](https://reactnavigation.org/docs/group/#screen-layout) which perfectly fits into a scenario mentioned as an example in React Navigation page.
=> docs: update React Navigation page

.changeset/real-ways-design.md, packages/init/src/bin.ts, packages/init/src/index.ts, packages/init/src/tasks/selectBundler.ts, packages/init/src/utils/isTruthyEnv.ts
Adds a prompt to choose a bundler:
=> feat(init): add choose bundler prompt

packages/plugin-nativewind/README.md
Updated links to properly guide user in Nativewind integration.
=> chore: update links in `packages/plugin-nativewind/README.md`

.changeset/late-geese-accept.md, packages/init/src/tasks/modifyIOS.ts, packages/repack/commands.js
backport https://github.com/callstack/repack/pull/869 into 4.x
n/a
=> [4.x] fix: bundling for release on RN 76

website/src/5.x/docs/guides/_meta.json, website/src/5.x/docs/guides/expo-modules.mdx
added docs for integrating `expo-modules` for V5 of Re.Pack
n/a
=> docs: expo-modules

website/src/5.x/docs/resources/glossary.md
copied over glossary docs from v4 over to v5 for now
n/a
=> docs: glossary

apps/tester-app/src/nativewind/ui/Button.tsx
Make `tester-app` build correctly 👍
=> fix: remove unnecessary web styles

.npmrc, website/src/5.x/api/cli/bundle.md, website/src/5.x/api/cli/start.md
added info blocks to the CLI docs about commands that are included for compatibility reasons
n/a
=> docs: add compat flags to command docs

pnpm-lock.yaml, website/package.json
=> chore: upgrade rspress to 1.40.2

.github/workflows/test.yml
Skips tests when change only in `website/`
=> ci: skip tests when only website changes

.changeset/mighty-dots-build.md, packages/repack/src/commands/rspack/start.ts, packages/repack/src/commands/webpack/start.ts
Solves a bug when a dev server breaks in totally unexpected place.
=> fix: add missing try/catch condition

.changeset/tender-suits-cross.md, packages/repack/android/src/main/java/com/callstack/repack/RemoteScriptLoader.kt
=> fix: reuse scriptsDir

apps/tester-app/package.json, apps/tester-federation-v2/package.json, apps/tester-federation/package.json, packages/plugin-expo-modules/package.json, packages/plugin-nativewind/package.json, packages/plugin-reanimated/package.json, packages/repack/package.json, pnpm-lock.yaml, pnpm-workspace.yaml
updated rspack and added it to catalog
n/a
=> chore: update rspack across repo, add it to catalog

.gitignore, biome.jsonc, package.json, packages/repack/src/types/runtime-globals.d.ts, pnpm-lock.yaml
upgraded biome to newest versions since 1.9.2 was sometimes causing issues with the vscode extension
n/a
=> chore: upgrade biome

.changeset/thin-birds-return.md, packages/repack/package.json, packages/repack/src/commands/common/config/getConfigFilePath.ts, packages/repack/src/commands/common/error.ts, packages/repack/src/commands/common/exit.ts, packages/repack/src/commands/rspack/Compiler.ts, packages/repack/src/commands/rspack/bundle.ts, packages/repack/src/commands/rspack/start.ts, packages/repack/src/commands/webpack/Compiler.ts, packages/repack/src/commands/webpack/bundle.ts, packages/repack/src/commands/webpack/start.ts, pnpm-lock.yaml
Before:
```
❯ npx react-native start --platform andr
error Unrecognized platform: andr.
Error: Unrecognized platform: andr
at Object.start [as func] (/Users/szymonrybczak/callstack/repack/packages/repack/dist/commands/rspack/start.js:57:11)
at Command.handleAction (/Users/szymonrybczak/callstack/repack/node_modules/.pnpm/@react-native-community+cli@15.0.1_typescript@5.7.2/node_modules/@react-native-community/cli/build/index.js:118:23)
at Command.listener [as _actionHandler] (/Users/szymonrybczak/callstack/repack/node_modules/.pnpm/commander@9.5.0/node_modules/commander/lib/command.js:482:17)
at /Users/szymonrybczak/callstack/repack/node_modules/.pnpm/commander@9.5.0/node_modules/commander/lib/command.js:1283:65
at Command._chainOrCall …
```
=> feat(cli): improve error handling

.changeset/light-turtles-destroy.md, packages/repack/src/plugins/LoggerPlugin.ts, packages/repack/src/plugins/RepackPlugin.ts
=> refactor: remove unused platform param from LoggerPlugin

website/src/5.x/api/cli/init.mdx, website/src/5.x/docs/getting-started/_meta.json, website/src/5.x/docs/getting-started/manual-installation.mdx, website/src/5.x/docs/getting-started/quick-start.mdx
Fixes https://github.com/callstack/repack/issues/915
=> docs: rework Quick start

website/src/5.x/api/plugins/_meta.json, website/src/5.x/api/plugins/module-federation-v2.md, website/src/5.x/api/plugins/module-federation-v2.mdx
Closes https://github.com/callstack/repack/issues/938
n/a
=> docs: ModuleFederationV2Plugin docs

website/src/5.x/api/plugins/module-federation-v2.mdx
=> docs: update differences section in MF2 plugin

website/src/5.x/api/plugins/_meta.json, website/src/5.x/api/plugins/module-federation-v1.mdx
Closes https://github.com/callstack/repack/issues/937
mostly copied over from V2, added deprecation notice and links to MF2 to further discourage the use of it.
n/a
=> docs: ModuleFederationV1Plugin

website/src/5.x/docs/guides/inline-assets.md
Closes https://github.com/callstack/repack/issues/926
n/a
=> docs: update inlining assets guide

website/src/5.x/api/plugins/code-signing.md
Closes https://github.com/callstack/repack/issues/933
n/a
=> docs: update code-signing plugin

website/src/5.x/api/loaders/assets-loader.md
Closes https://github.com/callstack/repack/issues/932
n/a
=> docs: update assets loader 

website/src/latest/docs/migration-guides/repack-v4.mdx
Closes https://github.com/callstack/repack/issues/930
n/a
=> docs: migration from v4

website/rspress.config.ts
=> chore: rspress enhancements

website/rspress.config.ts, website/src/latest/api/loaders/assets-loader.md, website/src/latest/api/utils/get-asset-transform-rules.md, website/src/latest/api/utils/get-resolve-options.md, website/src/latest/docs/getting-started/introduction.md, website/src/latest/docs/getting-started/quick-start.mdx, website/src/latest/docs/guides/inline-assets.md, website/src/latest/docs/guides/remote-assets.md, website/src/latest/docs/guides/svg.md, website/src/latest/docs/migration-guides/metro.mdx, website/src/latest/docs/migration-guides/repack-v4.mdx, website/src/latest/docs/migration-guides/rspack.mdx, website/src/latest/docs/resources/glossary.md
fixed all dead links on all versions of docs
n/a
=> chore: fix dead links in docs

website/src/latest/_meta.json, website/src/latest/blog/_meta.json, website/src/latest/blog/index.mdx, website/src/latest/blog/release-repack-5.mdx, website/theme/index.tsx
=> docs: add blog

website/src/latest/_meta.json
removed link to examples repo since they are not up to date and we will work on this later this quater
n/a
=> chore: remove examples

website/src/latest/public/img/banner.svg
=> docs: use gradient in logo

.changeset/config.json
adjusted changeset config to have every package on the same version
n/a
=> chore: fixed versions of all plugins

website/src/latest/docs/migration-guides/rspack.mdx
I was migrating my project to Re.Pack v5 and found some issues in docs.
=> docs: fix ReanimatedPlugin import

website/src/latest/docs/guides/bundle-analysis.md, website/src/latest/docs/guides/bundle-analysis.mdx
Closes https://github.com/callstack/repack/issues/925
=> docs: add bundle analysis

packages/repack/src/modules/FederationRuntimePlugins/__tests__/CorePlugin.test.ts
added tests for `RepackCorePlugin`
=> test: repack core plugin tests

README.md
=> docs: add branded banner

README.md
=> chore: add utm to banner link

website/src/latest/docs/getting-started/quick-start.mdx
=> docs: add minimum requirements to `quick-start`

apps/tester-app/android/build.gradle, apps/tester-federation-v2/android/build.gradle, apps/tester-federation/android/build.gradle
=> chore: align build.gradle in testers

.changeset/ninety-cats-float.md, packages/repack/src/commands/rspack/profile/index.ts, packages/repack/src/commands/rspack/profile/profile-1.4.ts, packages/repack/src/commands/rspack/profile/profile-legacy.ts, packages/repack/src/commands/rspack/start.ts
=> feat: support rspack 1.4 profiling

website/src/latest/api/plugins/code-signing.md
Inserted entry about the passphrase
=> docs: update code signing plugin docs 

website/theme/index.tsx, website/tsconfig.json
=> docs: remove announcement

pnpm-lock.yaml, website/package.json
=> chore: bump docs theme

mise.toml, package.json
=> chore: add mise config

.changeset/sixty-poets-admire.md, packages/init/versions.json
=> feat: declare support for RN 80

apps/tester-federation-v2/package.json, apps/tester-federation/package.json, pnpm-lock.yaml, pnpm-workspace.yaml
=> chore: update testers dependencies
